### ISSUE TITLE
NPE when importing diagram from database (NB 8.2)

### ISSUE THREAD

**Issue by mbppower** [jGauravGupta/JPAModeler#114]
Message : org.netbeans.modeler.widget.node.vmd.internal.AbstractPNodeWidget.<init>(AbstractPNodeWidget.java:96)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.modeler.widget.node.vmd.internal.AbstractPNodeWidget.<init>(AbstractPNodeWidget.java:96)
	at org.netbeans.modeler.widget.node.vmd.PNodeWidget.<init>(PNodeWidget.java:142)
	at org.netbeans.jpa.modeler.core.widget.FlowNodeWidget.<init>(FlowNodeWidget.java:40)
	at org.netbeans.jpa.modeler.core.widget.JavaClassWidget.<init>(JavaClassWidget.java:64)
	at org.netbeans.jpa.modeler.core.widget.PersistenceClassWidget.<init>(PersistenceClassWidget.java:163)
	at org.netbeans.jpa.modeler.core.widget.PrimaryKeyContainerWidget.<init>(PrimaryKeyContainerWidget.java:30)
	at org.netbeans.jpa.modeler.core.widget.EntityWidget.<init>(EntityWidget.java:52)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.attachNodeWidget(JPAModelerUtil.java:1058)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.attachNodeWidget(JPAModelerUtil.java:195)
	at org.netbeans.modeler.scene.vmd.AbstractPModelerScene.attachNodeWidget(AbstractPModelerScene.java:196)
	at org.netbeans.modeler.scene.vmd.AbstractPModelerScene.attachNodeWidget(AbstractPModelerScene.java:97)
	at org.netbeans.api.visual.graph.GraphPinScene.addNode(GraphPinScene.java:103)
	at org.netbeans.modeler.scene.vmd.AbstractPModelerScene.createNodeWidget(AbstractPModelerScene.java:824)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.loadFlowNode(JPAModelerUtil.java:562)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.lambda$loadModelerFile$0(JPAModelerUtil.java:456)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.loadModelerFile(JPAModelerUtil.java:456)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:143)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:72)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:64)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.lambda$actionPerformed$0(ModelerFileActionListener.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1086)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1136)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1108)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:131)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:138)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:98)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:94)
	at org.openide.util.Mutex.readAccess(Mutex.java:218)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1093)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.modules.j2ee.persistence.wizard.fromdb.ProgressPanel.open(ProgressPanel.java:83)
	at org.netbeans.jpa.modeler.reveng.database.DBImportWizardDescriptor$2.run(DBImportWizardDescriptor.java:121)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" v="2.8" status="GENERATED" sm="false" xs="false" id="_1483452661580636" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity xre="false" abs="false" class="AcceptedPaymentMethod" v="true" minimized="false" rootElement="_1483452661580636" id="_1483452661580637">
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="String" v="true" name="name" id="_1483452661581639">
                <jpa:bv/>
                <jpa:column name="name" unique="false" nullable="true" insertable="true" updatable="true" table="accepted_payment_method" length="255"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="key" id="_1483452661581640">
                <jpa:bv/>
                <jpa:column name="key" unique="false" nullable="true" insertable="true" updatable="true" table="accepted_payment_method" length="255"/>
            </jpa:basic>
            <jpa:id attribute-type="Long" v="true" name="id" id="_1483452661581638">
                <jpa:bv/>
                <jpa:column name="id" unique="false" nullable="false" insertable="true" updatable="true" table="accepted_payment_method"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="accepted_payment_method"/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:inf e="true" n="java.io.Serializable"/>
    <jpa:diagram>
        <plane elementRef="_1483452661580636"/>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Hi @mbppower ,

Are you using any third party theme like Darcula LAF.
If using then can you please try it without theme(with default netbeans theme).

**Comment by mbppower** [comment]
Yes I was using Darcula LAF, disabling it solved the problem. Thanks.

**Comment by jGauravGupta** [comment]
Hi @mbppower ,

I am not able to reproduce it so Can you please attach the Darcula LAF plugin here and share your development environment details like OS etc.

**Duplicate Issue :** https://github.com/jGauravGupta/JPAModeler/issues/73, https://github.com/jGauravGupta/JPAModeler/issues/93
