### ISSUE TITLE
NB8.2 + Plugin 2.7.2, 2.8, 3.0 - failed to create/open jpa model

### ISSUE THREAD

**Issue by ReneKuzica** [jGauravGupta/JPAModeler#124]
Message : org.netbeans.modeler.component.ModelerPanelTopComponent.initLookup(ModelerPanelTopComponent.java:112)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.modeler.component.ModelerPanelTopComponent.initLookup(ModelerPanelTopComponent.java:112)
	at org.netbeans.modeler.component.ModelerPanelTopComponent.init(ModelerPanelTopComponent.java:92)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:140)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:72)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:64)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.lambda$actionPerformed$0(ModelerFileActionListener.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml

```

**Comment by jGauravGupta** [comment]
Please share the netbeans build detail (Help > About) and JPA Modeler
version.
Can you share detail about => "Plugin 2.7.2, 2.8, 3.8" ?

**Comment by ReneKuzica** [comment]
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: Updates available to version NetBeans 8.2 Patch 1
Java: 1.8.0_112; Java HotSpot(TM) 64-Bit Server VM 25.112-b15
Runtime: Java(TM) SE Runtime Environment 1.8.0_112-b15
System: Windows 7 version 6.1 running on amd64; Cp1250; en_US (nb)
User directory: C:\Users\z0002wjj\AppData\Roaming\NetBeans\8.2
Cache directory: C:\Users\z0002wjj\AppData\Local\NetBeans\Cache\8.2

My NB8.1 with your JPA Modeler Plugin 2.6 is working fine. I tried to switch to NB8.2 build with JPA Modeler Plugin 2.8, but this combination failed. So I tried 2.7.2 and 3.0, but the same result.

**Comment by jGauravGupta** [comment]
Have you imported NB8.1 settings at the installation time of NB8.2 ?



Thanks and kind regards,
Gaurav Gupta
<https://twitter.com/intent/follow?original_referer=https%3A%2F%2Fabout.twitter.com%2Fresources%2Fbuttons&ref_src=twsrc%5Etfw&region=follow_link&screen_name=jpamodeler&tw_p=followbutton>
<http://jpamodeler.github.io/>   <https://www.youtube.com/JPAModeler>

**Comment by ReneKuzica** [comment]
Yes, I made import of all compatible plugins, which I had in NB8.1, but JPA was not working. So I've uninstalled it from plugins and installed JPA 2.8. for NB8.2, and tried 3.0 too, but the same result.

**Comment by jGauravGupta** [comment]
JPA Modeler have multiple module (22 plugins) with different name looks
like you have not un-installed all module of JPA Modeler.
Can you check by installing new copy of NB8.2 in different directory
without importing previous configuration then install the JPA Modeler v3.0
(22 plugins).

**Comment by ReneKuzica** [comment]
Thank you for your idea, finally it's working. I've deleted all 22 modules (jars with their appropriate xml config files) from installation folder NB8.2\jcode\... and then install JPA Modeler 3.0 again.
