### ISSUE TITLE
DB Modeler - DBValidationException [OneToOne-DerivedId]

### ISSUE THREAD

**Issue by MHTaleb** [jGauravGupta/JPAModeler#141]
Message : Exception Description: 

StackTrace : 
Local Exception Stack: 
Exception [EclipseLink-0] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.netbeans.db.modeler.exception.DBValidationException
Exception Description: 
	at org.netbeans.jpa.modeler.db.accessor.OneToOneSpecAccessor.process(OneToOneSpecAccessor.java:78)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processDerivedId(ClassAccessor.java:1619)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processDerivedId(EntityAccessor.java:993)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processAccessorsWithDerivedIDs(MetadataProject.java:1539)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage3(MetadataProject.java:1836)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:577)
	at org.netbeans.db.modeler.persistence.internal.jpa.deployment.JPAMPersistenceUnitProcessor.processORMetadata(JPAMPersistenceUnitProcessor.java:49)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:255)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:193)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:178)
	at org.netbeans.db.modeler.specification.model.util.DeploymentExceptionManager.handleException(DeploymentExceptionManager.java:94)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:183)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:143)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:58)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1566)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$4(JPAModelerScene.java:384)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.talcorp.piecedetachee.dalipiecesdetacheesfinal" v="2.6" status="GENERATED" sm="false" xs="false" id="_14873642170001" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity xre="false" abs="false" class="Factures" visibile="true" minimized="false" rootElement="_14873642170001" id="_14873642170532">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="date" id="_14873642170534">
                <jpa:bv/>
                <jpa:temporal>DATE</jpa:temporal>
                <jpa:column name="DATE"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="idFournisseur" id="_14873642170695">
                <jpa:bv/>
                <jpa:column name="ID_FOURNISSEUR"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="montantGlobal" id="_14873642170696">
                <jpa:bv/>
                <jpa:column name="MONTANT_GLOBAL"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_14873642170533">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Factures.findAll">
            <jpa:query>SELECT f FROM Factures f</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Factures.findById">
            <jpa:query>SELECT f FROM Factures f WHERE f.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Factures.findByDate">
            <jpa:query>SELECT f FROM Factures f WHERE f.date = :date</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Factures.findByIdFournisseur">
            <jpa:query>SELECT f FROM Factures f WHERE f.idFournisseur = :idFournisseur</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Factures.findByMontantGlobal">
            <jpa:query>SELECT f FROM Factures f WHERE f.montantGlobal = :montantGlobal</jpa:query>
        </jpa:nq>
        <jpa:table name="factures"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Produits" visibile="true" minimized="false" rootElement="_14873642170001" id="_14873642171157">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="titre" id="_14873642171159">
                <jpa:bv/>
                <jpa:column name="TITRE"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="int" visibile="true" name="qtMin" id="_148736421711510">
                <jpa:bv/>
                <jpa:column name="QT_MIN"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="codebar" id="_148736421711511">
                <jpa:bv/>
                <jpa:column name="CODEBAR"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="detail" id="_148736421711512">
                <jpa:bv/>
                <jpa:column name="DETAIL"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_14873642171158">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Produits.findAll">
            <jpa:query>SELECT p FROM Produits p</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Produits.findById">
            <jpa:query>SELECT p FROM Produits p WHERE p.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Produits.findByTitre">
            <jpa:query>SELECT p FROM Produits p WHERE p.titre = :titre</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Produits.findByQtMin">
            <jpa:query>SELECT p FROM Produits p WHERE p.qtMin = :qtMin</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Produits.findByCodebar">
            <jpa:query>SELECT p FROM Produits p WHERE p.codebar = :codebar</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Produits.findByDetail">
            <jpa:query>SELECT p FROM Produits p WHERE p.detail = :detail</jpa:query>
        </jpa:nq>
        <jpa:table name="produits"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Users" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421713813">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="int" visibile="true" name="state" id="_148736421713815">
                <jpa:bv/>
                <jpa:column name="STATE"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="username" id="_148736421713816">
                <jpa:bv/>
                <jpa:column name="USERNAME"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="password" id="_148736421713817">
                <jpa:bv/>
                <jpa:column name="PASSWORD"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="profile" id="_148736421713818">
                <jpa:bv/>
                <jpa:column name="PROFILE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421713814">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Users.findAll">
            <jpa:query>SELECT u FROM Users u</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Users.findById">
            <jpa:query>SELECT u FROM Users u WHERE u.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Users.findByState">
            <jpa:query>SELECT u FROM Users u WHERE u.state = :state</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Users.findByUsername">
            <jpa:query>SELECT u FROM Users u WHERE u.username = :username</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Users.findByPassword">
            <jpa:query>SELECT u FROM Users u WHERE u.password = :password</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Users.findByProfile">
            <jpa:query>SELECT u FROM Users u WHERE u.profile = :profile</jpa:query>
        </jpa:nq>
        <jpa:table name="users"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Usersstate" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421720019">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="titre" id="_148736421720021">
                <jpa:bv/>
                <jpa:column name="TITRE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421720020">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Usersstate.findAll">
            <jpa:query>SELECT u FROM Usersstate u</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Usersstate.findById">
            <jpa:query>SELECT u FROM Usersstate u WHERE u.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Usersstate.findByTitre">
            <jpa:query>SELECT u FROM Usersstate u WHERE u.titre = :titre</jpa:query>
        </jpa:nq>
        <jpa:table name="usersstate"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Vente" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421723822">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="Integer" visibile="true" name="idProduit" id="_148736421723824">
                <jpa:bv/>
                <jpa:column name="ID_PRODUIT"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="prixFinal" id="_148736421723825">
                <jpa:bv/>
                <jpa:column name="PRIX_FINAL"/>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="date" id="_148736421723826">
                <jpa:bv/>
                <jpa:temporal>DATE</jpa:temporal>
                <jpa:column name="DATE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421723823">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Vente.findAll">
            <jpa:query>SELECT v FROM Vente v</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Vente.findById">
            <jpa:query>SELECT v FROM Vente v WHERE v.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Vente.findByIdProduit">
            <jpa:query>SELECT v FROM Vente v WHERE v.idProduit = :idProduit</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Vente.findByPrixFinal">
            <jpa:query>SELECT v FROM Vente v WHERE v.prixFinal = :prixFinal</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Vente.findByDate">
            <jpa:query>SELECT v FROM Vente v WHERE v.date = :date</jpa:query>
        </jpa:nq>
        <jpa:table name="vente"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Categories" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421733827">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="titreCategorie" id="_148736421733829">
                <jpa:bv/>
                <jpa:column name="TITRE_CATEGORIE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421733828">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Categories.findAll">
            <jpa:query>SELECT c FROM Categories c</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Categories.findById">
            <jpa:query>SELECT c FROM Categories c WHERE c.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Categories.findByTitreCategorie">
            <jpa:query>SELECT c FROM Categories c WHERE c.titreCategorie = :titreCategorie</jpa:query>
        </jpa:nq>
        <jpa:table name="categories"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Profiles" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421738530">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="titre" id="_148736421738532">
                <jpa:bv/>
                <jpa:column name="TITRE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421738531">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Profiles.findAll">
            <jpa:query>SELECT p FROM Profiles p</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Profiles.findById">
            <jpa:query>SELECT p FROM Profiles p WHERE p.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Profiles.findByTitre">
            <jpa:query>SELECT p FROM Profiles p WHERE p.titre = :titre</jpa:query>
        </jpa:nq>
        <jpa:table name="profiles"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="ProduitMarque" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421745433">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="Integer" visibile="true" name="idProduit" id="_148736421745435">
                <jpa:bv/>
                <jpa:column name="ID_PRODUIT"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="idMarque" id="_148736421745436">
                <jpa:bv/>
                <jpa:column name="ID_MARQUE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421745434">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="ProduitMarque.findAll">
            <jpa:query>SELECT p FROM ProduitMarque p</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="ProduitMarque.findById">
            <jpa:query>SELECT p FROM ProduitMarque p WHERE p.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="ProduitMarque.findByIdProduit">
            <jpa:query>SELECT p FROM ProduitMarque p WHERE p.idProduit = :idProduit</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="ProduitMarque.findByIdMarque">
            <jpa:query>SELECT p FROM ProduitMarque p WHERE p.idMarque = :idMarque</jpa:query>
        </jpa:nq>
        <jpa:table name="produit_marque"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="ProduitCategorie" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421747037">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="Integer" visibile="true" name="idProduit" id="_148736421747039">
                <jpa:bv/>
                <jpa:column name="ID_PRODUIT"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="idCategorie" id="_148736421747040">
                <jpa:bv/>
                <jpa:column name="ID_CATEGORIE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421747038">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="ProduitCategorie.findAll">
            <jpa:query>SELECT p FROM ProduitCategorie p</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="ProduitCategorie.findById">
            <jpa:query>SELECT p FROM ProduitCategorie p WHERE p.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="ProduitCategorie.findByIdProduit">
            <jpa:query>SELECT p FROM ProduitCategorie p WHERE p.idProduit = :idProduit</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="ProduitCategorie.findByIdCategorie">
            <jpa:query>SELECT p FROM ProduitCategorie p WHERE p.idCategorie = :idCategorie</jpa:query>
        </jpa:nq>
        <jpa:table name="produit_categorie"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Fournisseur" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421750141">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="nom" id="_148736421750143">
                <jpa:bv/>
                <jpa:column name="NOM"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="prenom" id="_148736421750144">
                <jpa:bv/>
                <jpa:column name="PRENOM"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="adresse" id="_148736421750145">
                <jpa:bv/>
                <jpa:column name="ADRESSE"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="telephone" id="_148736421750146">
                <jpa:bv/>
                <jpa:column name="TELEPHONE"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="marqueCommercial" id="_148736421750147">
                <jpa:bv/>
                <jpa:column name="MARQUE_COMMERCIAL"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421750142">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Fournisseur.findAll">
            <jpa:query>SELECT f FROM Fournisseur f</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Fournisseur.findById">
            <jpa:query>SELECT f FROM Fournisseur f WHERE f.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Fournisseur.findByNom">
            <jpa:query>SELECT f FROM Fournisseur f WHERE f.nom = :nom</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Fournisseur.findByPrenom">
            <jpa:query>SELECT f FROM Fournisseur f WHERE f.prenom = :prenom</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Fournisseur.findByAdresse">
            <jpa:query>SELECT f FROM Fournisseur f WHERE f.adresse = :adresse</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Fournisseur.findByTelephone">
            <jpa:query>SELECT f FROM Fournisseur f WHERE f.telephone = :telephone</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Fournisseur.findByMarqueCommercial">
            <jpa:query>SELECT f FROM Fournisseur f WHERE f.marqueCommercial = :marqueCommercial</jpa:query>
        </jpa:nq>
        <jpa:table name="fournisseur"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Marques" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421753948">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="titreMarques" id="_148736421753950">
                <jpa:bv/>
                <jpa:column name="TITRE_MARQUES"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421753949">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Marques.findAll">
            <jpa:query>SELECT m FROM Marques m</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Marques.findById">
            <jpa:query>SELECT m FROM Marques m WHERE m.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Marques.findByTitreMarques">
            <jpa:query>SELECT m FROM Marques m WHERE m.titreMarques = :titreMarques</jpa:query>
        </jpa:nq>
        <jpa:table name="marques"/>
    </jpa:entity>
    <jpa:entity xre="false" abs="false" class="Approvisionement" visibile="true" minimized="false" rootElement="_14873642170001" id="_148736421760151">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="int" visibile="true" name="idFacture" id="_148736421760153">
                <jpa:bv/>
                <jpa:column name="ID_FACTURE"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="int" visibile="true" name="idProduit" id="_148736421760154">
                <jpa:bv/>
                <jpa:column name="ID_PRODUIT"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="quantite" id="_148736421760155">
                <jpa:bv/>
                <jpa:column name="QUANTITE"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="prixAchat" id="_148736421760156">
                <jpa:bv/>
                <jpa:column name="PRIX_ACHAT"/>
            </jpa:basic>
            <jpa:basic attribute-type="Integer" visibile="true" name="prixVente" id="_148736421760157">
                <jpa:bv/>
                <jpa:column name="PRIX_VENTE"/>
            </jpa:basic>
            <jpa:id attribute-type="Integer" visibile="true" name="id" id="_148736421760152">
                <jpa:bv/>
                <jpa:column name="ID"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Approvisionement.findAll">
            <jpa:query>SELECT a FROM Approvisionement a</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Approvisionement.findById">
            <jpa:query>SELECT a FROM Approvisionement a WHERE a.id = :id</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Approvisionement.findByIdFacture">
            <jpa:query>SELECT a FROM Approvisionement a WHERE a.idFacture = :idFacture</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Approvisionement.findByIdProduit">
            <jpa:query>SELECT a FROM Approvisionement a WHERE a.idProduit = :idProduit</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Approvisionement.findByQuantite">
            <jpa:query>SELECT a FROM Approvisionement a WHERE a.quantite = :quantite</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Approvisionement.findByPrixAchat">
            <jpa:query>SELECT a FROM Approvisionement a WHERE a.prixAchat = :prixAchat</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Approvisionement.findByPrixVente">
            <jpa:query>SELECT a FROM Approvisionement a WHERE a.prixVente = :prixVente</jpa:query>
        </jpa:nq>
        <jpa:table name="approvisionement"/>
    </jpa:entity>
    <jpa:snp e="true" loc="BEFORE_PACKAGE">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:diagram>
        <plane elementRef="_14873642170001"/>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Please upload the valid modeler file, The attached file does not have any entity with one-to-one relationship attribute.

**Comment by jGauravGupta** [comment]
Hi @MHTaleb ,

Please upload the valid modeler file to reproduce it.
