### ISSUE TITLE
DB modeler fails with external classes used

### ISSUE THREAD

**Issue by slavb18** [jGauravGupta/JPAModeler#149]
I have dependency
```xml
        <dependency>
            <groupId>com.vividsolutions</groupId>
            <artifactId>jts-io</artifactId>
            <version>1.14.0</version>
        </dependency>
```
and field 
```
    @Column(columnDefinition="GEOMETRY")
    @Basic
    private Geometry geo;
```
DB modeler fails with external classes

Message : com/vividsolutions/jts/geom/Geometry

StackTrace : 
java.lang.NoClassDefFoundError: com/vividsolutions/jts/geom/Geometry
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at org.eclipse.persistence.internal.security.PrivilegedAccessHelper.getDeclaredMethods(PrivilegedAccessHelper.java:339)
	at org.eclipse.persistence.internal.jpa.metadata.listeners.EntityListenerMetadata.getDeclaredMethods(EntityListenerMetadata.java:249)
	at org.eclipse.persistence.internal.jpa.metadata.listeners.EntityClassListenerMetadata.process(EntityClassListenerMetadata.java:89)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processListeners(EntityAccessor.java:1226)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.addEntityListeners(MetadataProcessor.java:140)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:252)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:186)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:171)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:62)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:154)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:58)
	at org.netbeans.jpa.modeler.specification.model.util.DBUtil.openDBViewer(DBUtil.java:87)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$3(JPAModelerScene.java:384)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3315)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.ClassNotFoundException: com.vividsolutions.jts.geom.Geometry
	at java.lang.ClassLoader.findClass(ClassLoader.java:530)
	at org.eclipse.persistence.dynamic.DynamicClassLoader.findClass(DynamicClassLoader.java:226)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.netbeans.db.modeler.classloader.DynamicDriverClassLoader.loadClass(DynamicDriverClassLoader.java:56)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 55 more

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="ru.ilb.jparestresource.model" v="3.1" rws="_14881688460591" Pws="_14881688460591" cws="_14881688460591" persistenceUnitName="jparestresource" sm="false" xs="true" id="_14855761330684" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:description>jparestresource model</jpa:description>
    <jpa:entity xre="true" compositePrimaryKeyClass="DocfilePK" abs="false" class="Docfile" v="true" m="false" rootElement="_14855761330684" id="_14855761330685">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="String" v="true" name="comment" id="_14855761330778">
                <jpa:des>File comment</jpa:des>
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="Boolean" v="true" name="confirm" id="_14855761330779">
                <jpa:des>Confirmation status</jpa:des>
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="userName" id="_148557613307711">
                <jpa:des>User created</jpa:des>
                <jpa:bv/>
            </jpa:basic>
            <jpa:many-to-one optional="true" primaryKey="false" connected-entity-id="_14855761330696" connected-attribute-id="_148557613307823" v="true" xvt="I_E" name="document" id="_148557613307714">
                <jpa:bv/>
                <jpa:join-column name="DOCUMENT_ID" rc="ID" unique="false" nullable="false" insertable="true" updatable="true" column-definition="" table=""/>
            </jpa:many-to-one>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14855761330767">
                <jpa:bv/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="DOCFILE"/>
    </jpa:entity>
    <jpa:entity xre="true" compositePrimaryKeyClass="DocumentPK" abs="false" class="Document" v="true" m="false" rootElement="_14855761330684" id="_14855761330696">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="String" v="true" xvt="E" name="displayName" id="_148557613307718">
                <jpa:des>Document name</jpa:des>
                <jpa:xe nillable="false" required="false"/>
                <jpa:bv>
                    <jpa:si mi="1" ma="255" m="must be beweeen 1 and 255 chars"/>
                </jpa:bv>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="description" id="_148557613307716">
                <jpa:des>Document description</jpa:des>
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.time.LocalDate" v="true" name="docDate" id="_148557613307719">
                <jpa:des>Document date</jpa:des>
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="com.vividsolutions.jts.geom.Geometry" v="true" name="geo" id="_1488523570571646">
                <jpa:bv/>
                <jpa:column unique="false" nullable="true" insertable="true" updatable="true" column-definition="GEOMETRY"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_14855761330685" connected-attribute-id="_148557613307714" v="true" name="docfiles" id="_148557613307823">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_148557613307715">
                <jpa:bv/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Document.findByGeo">
            <jpa:query>Select d from Document d where d.geo=:geo</jpa:query>
        </jpa:nq>
        <jpa:el/>
        <jpa:table name="DOCUMENT"/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:inf e="true" n="java.io.Serializable"/>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14881688460591">
            <i ref="_14855761330685" x="419" y="190"/>
            <i ref="_14855761330696" x="145" y="74"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Try latest v3.4 
https://github.com/jGauravGupta/JPAModeler/releases/tag/3.4
Ref : https://github.com/jGauravGupta/JPAModeler/issues/37

**Comment by slavb18** [comment]
Thanks again, confirm working in 3.4
