### ISSUE TITLE
Error while generating source code (Docker)

### ISSUE THREAD

**Issue by nieled** [jGauravGupta/JPAModeler#158]
I just ran into a problem when following this example: https://jpamodeler.github.io/page.html?l=tutorial/Docker
I'm using a local docker implementation and made no other changes.

Message : `java.util.Hashtable.put(Hashtable.java:459)`

StackTrace : 
```
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at org.jcode.docker.generator.DockerGenerator.addMavenDependencies(DockerGenerator.java:173)
	at org.jcode.docker.generator.DockerGenerator.execute(DockerGenerator.java:102)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generateCRUD(ApplicationGenerator.java:198)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generate(ApplicationGenerator.java:75)
	at org.netbeans.jcode.generator.JEEApplicationGenerator.generate(JEEApplicationGenerator.java:42)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:113)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:78)
	at org.netbeans.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:447)
	at org.netbeans.jcode.task.AbstractNBTask.run(AbstractNBTask.java:88)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings pkg="com.nieled.shoppingmodule.domain" v="3.5.1" rws="_14890685670922" Pws="_14890685670922" cws="_14890685670922" sm="false" xs="false" id="_14890685670911" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductPK" abs="false" class="Product" v="true" m="false" rootElement="_14890685670911" id="_1489068573909">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>niel</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="String" v="true" name="name" id="_14890686062405">
                <jpa:bv/>
            </jpa:basic>
            <jpa:many-to-many collection-type="java.util.List" connected-entity-id="_1489068610059" connected-attribute-id="_148906866776910" v="true" name="productOrders" id="_148906866777011">
                <jpa:bv/>
            </jpa:many-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14890685739503">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Product.findAll">
            <jpa:query>Select e from Product e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByName">
            <jpa:query>Select p from Product p where p.name=:name</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductOrderPK" abs="false" class="ProductOrder" v="true" m="false" rootElement="_14890685670911" id="_1489068610059">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>niel</jpa:ath>
        <jpa:attributes>
            <jpa:basic attribute-type="int" v="true" name="amount" id="_14890686452159">
                <jpa:bv/>
            </jpa:basic>
            <jpa:many-to-many own="true" collection-type="java.util.List" connected-entity-id="_1489068573909" connected-attribute-id="_148906866777011" v="true" name="products" id="_148906866776910">
                <jpa:bv/>
            </jpa:many-to-many>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14890686100606">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="ProductOrder.findAll">
            <jpa:query>Select e from ProductOrder e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ProductOrder.findByAmount">
            <jpa:query>Select p from ProductOrder p where p.amount=:amount</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14890685670922">
            <i ref="_1489068573909" x="359" y="199"/>
            <i ref="_1489068610059" x="646" y="343"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Hi @nieled , 
Thanks for reporting the issue.

**Comment by jGauravGupta** [comment]
Hi @nieled ,

Any specific reason , you closed the issue ?
