### ISSUE TITLE
NPE in Source code generation

### ISSUE THREAD

**Issue by jGauravGupta** [jGauravGupta/JPAModeler#162]
Message : org.netbeans.jpa.modeler.spec.extend.Attribute.getJavaClass(Attribute.java:330)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.jpa.modeler.spec.extend.Attribute.getJavaClass(Attribute.java:330)
	at org.netbeans.orm.converter.generator.ClassGenerator.lambda$null$1(ClassGenerator.java:351)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.netbeans.orm.converter.generator.ClassGenerator.lambda$getConstructorSnippets$3(ClassGenerator.java:351)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.netbeans.orm.converter.generator.ClassGenerator.getConstructorSnippets(ClassGenerator.java:356)
	at org.netbeans.orm.converter.generator.ClassGenerator.initClassDef(ClassGenerator.java:217)
	at org.netbeans.orm.converter.generator.DefaultClassGenerator.getClassDef(DefaultClassGenerator.java:41)
	at org.netbeans.orm.converter.generator.managed.ManagedClassModuleGeneratorImpl.generateEmbededIdClasses(ManagedClassModuleGeneratorImpl.java:136)
	at org.netbeans.orm.converter.generator.managed.ManagedClassModuleGeneratorImpl.generateDefaultClasses(ManagedClassModuleGeneratorImpl.java:84)
	at org.netbeans.orm.converter.generator.managed.ManagedClassModuleGeneratorImpl.generate(ManagedClassModuleGeneratorImpl.java:70)
	at org.netbeans.jpa.modeler.source.generator.adaptor.internal.JPASourceCodeGenerator.generate(JPASourceCodeGenerator.java:42)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:110)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:78)
	at org.netbeans.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:447)
	at org.netbeans.jcode.task.AbstractNBTask.run(AbstractNBTask.java:88)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="domain" v="3.5" rws="_14887077807782" Pws="_14887077807782" cws="_14887077807782" sm="false" xs="false" id="_14887077807781" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity lbl-ref="_14887077885693" xre="false" compositePrimaryKeyType="EMBEDDEDID" compositePrimaryKeyClass="Entity_1PK" abs="false" class="Entity_1" v="true" m="false" rootElement="_14887077807781" id="_1488707788360">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>jGauravGupta</jpa:ath>
        <jpa:attributes>
            <jpa:id attribute-type="Long" v="true" name="id" id="_14887077885693">
                <jpa:bv/>
                <jpa:generated-value/>
            </jpa:id>
            <jpa:id attribute-type="Long" v="true" name="id1" id="_14887077980017">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:embedded-id v="true" name="entity_1EmbeddedId" id="_14887092802818">
                <jpa:bv/>
            </jpa:embedded-id>
        </jpa:attributes>
        <jpa:nq e="false" name="Entity_1.findAll">
            <jpa:query>Select e from Entity_1 e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Entity_1.findByAttribute">
            <jpa:query>Select e from Entity_1 e where e.attribute=:attribute</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Entity_1.findByAttribute1">
            <jpa:query>Select e from Entity_1 e where e.attribute1=:attribute1</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Entity_1.findByAttribute2">
            <jpa:query>Select e from Entity_1 e where e.attribute2=:attribute2</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:entity lbl-ref="_1489351511022126" xre="false" compositePrimaryKeyType="D" compositePrimaryKeyClass="Entity_1PK" abs="false" class="Entity_2" v="true" m="false" rootElement="_14887077807781" id="_1488707791367">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:ath>jGauravGupta</jpa:ath>
        <jpa:attributes>
            <jpa:many-to-one primaryKey="true" maps-id="entity_14" connected-entity-id="_1488707788360" v="true" name="entity_14" id="_148871756910410">
                <jpa:bv/>
            </jpa:many-to-one>
            <jpa:one-to-one own="true" primaryKey="true" maps-id="entity_11" connected-entity-id="_1488707788360" v="true" name="entity_11" id="_14887175550935">
                <jpa:bv/>
            </jpa:one-to-one>
            <jpa:embedded-id v="true" name="entity_2EmbeddedId" id="_1489351511022126">
                <jpa:bv/>
            </jpa:embedded-id>
        </jpa:attributes>
        <jpa:nq e="false" name="Entity_2.findAll">
            <jpa:query>Select e from Entity_2 e</jpa:query>
        </jpa:nq>
        <jpa:el/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:wsl>
        <jpa:ws n="Main" id="_14887077807782">
            <i ref="_1488707791367" x="364" y="170"/>
            <i ref="_1488707788360" x="50" y="56"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Not reproducible with master branch.
