### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by olmayanaergi** [jGauravGupta/JPAModeler#163]
Message : java.util.Hashtable.put(Hashtable.java:459)

StackTrace : 
java.lang.NullPointerException
	at java.util.Hashtable.put(Hashtable.java:459)
	at org.jcode.docker.generator.DockerGenerator.addMavenDependencies(DockerGenerator.java:173)
	at org.jcode.docker.generator.DockerGenerator.execute(DockerGenerator.java:102)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generateCRUD(ApplicationGenerator.java:198)
	at org.netbeans.jcode.generator.internal.ApplicationGenerator.generate(ApplicationGenerator.java:75)
	at org.netbeans.jcode.generator.JEEApplicationGenerator.generate(JEEApplicationGenerator.java:42)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:113)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:78)
	at org.netbeans.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:447)
	at org.netbeans.jcode.task.AbstractNBTask.run(AbstractNBTask.java:88)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings pkg="com.mycompany.mavenproject2" v="3.5.1" rws="_1489411733983233" Pws="_1489411733983233" cws="_1489411733983233" sm="false" xs="false" id="_1489411733819171" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <jpa:entity xre="false" compositePrimaryKeyClass="MicroMarketPK" abs="false" class="MicroMarket" v="true" m="false" rootElement="_1489411733819171" id="_1489411733819172">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="Double" v="true" name="radius" id="_1489411733819180">
                <jpa:bv/>
                <jpa:column name="RADIUS" unique="false" nullable="true" insertable="true" updatable="true" table="MICRO_MARKET" precision="52"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="Double" v="true" name="areaLength" id="_1489411733819181">
                <jpa:bv/>
                <jpa:column name="AREA_LENGTH" unique="false" nullable="true" insertable="true" updatable="true" table="MICRO_MARKET" precision="52"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="Double" v="true" name="areaWidth" id="_1489411733819182">
                <jpa:bv/>
                <jpa:column name="AREA_WIDTH" unique="false" nullable="true" insertable="true" updatable="true" table="MICRO_MARKET" precision="52"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_1489411733819176" connected-attribute-id="_1489411733819216" v="true" name="customerCollection" id="_1489411733819183">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="String" v="true" name="zipCode" id="_1489411733819179">
                <jpa:bv/>
                <jpa:column name="ZIP_CODE" unique="false" nullable="false" insertable="true" updatable="true" table="MICRO_MARKET" length="10"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="MICRO_MARKET"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="DiscountCodePK" abs="false" class="DiscountCode" v="true" m="false" rootElement="_1489411733819171" id="_1489411733819173">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="java.math.BigDecimal" v="true" name="rate" id="_1489411733819185">
                <jpa:bv/>
                <jpa:column name="RATE" unique="false" nullable="true" insertable="true" updatable="true" table="DISCOUNT_CODE" precision="4" scale="2"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_1489411733819176" connected-attribute-id="_1489411733819215" v="true" name="customerCollection" id="_1489411733819186">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="String" v="true" name="discountCode" id="_1489411733819184">
                <jpa:bv/>
                <jpa:column name="DISCOUNT_CODE" unique="false" nullable="false" insertable="true" updatable="true" table="DISCOUNT_CODE" length="1"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="DISCOUNT_CODE"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="PurchaseOrderPK" abs="false" class="PurchaseOrder" v="true" m="false" rootElement="_1489411733819171" id="_1489411733819174">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="Short" v="true" name="quantity" id="_1489411733819188">
                <jpa:bv/>
                <jpa:column name="QUANTITY" unique="false" nullable="true" insertable="true" updatable="true" table="PURCHASE_ORDER"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.math.BigDecimal" v="true" name="shippingCost" id="_1489411733819189">
                <jpa:bv/>
                <jpa:column name="SHIPPING_COST" unique="false" nullable="true" insertable="true" updatable="true" table="PURCHASE_ORDER" precision="12" scale="2"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.util.Date" v="true" name="salesDate" id="_1489411733819190">
                <jpa:bv/>
                <jpa:temporal>DATE</jpa:temporal>
                <jpa:column name="SALES_DATE" unique="false" nullable="true" insertable="true" updatable="true" table="PURCHASE_ORDER"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.util.Date" v="true" name="shippingDate" id="_1489411733819191">
                <jpa:bv/>
                <jpa:temporal>DATE</jpa:temporal>
                <jpa:column name="SHIPPING_DATE" unique="false" nullable="true" insertable="true" updatable="true" table="PURCHASE_ORDER"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="freightCompany" id="_1489411733819192">
                <jpa:bv/>
                <jpa:column name="FREIGHT_COMPANY" unique="false" nullable="true" insertable="true" updatable="true" table="PURCHASE_ORDER" length="30"/>
            </jpa:basic>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_1489411733819176" connected-attribute-id="_1489411733819214" v="true" name="customerId" id="_1489411733819193">
                <jpa:bv/>
                <jpa:join-column name="CUSTOMER_ID" rc="CUSTOMER_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_1489411733819175" connected-attribute-id="_1489411733819201" v="true" name="productId" id="_1489411733819194">
                <jpa:bv/>
                <jpa:join-column name="PRODUCT_ID" rc="PRODUCT_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:id attribute-type="Integer" v="true" name="orderNum" id="_1489411733819187">
                <jpa:bv/>
                <jpa:column name="ORDER_NUM" unique="false" nullable="false" insertable="true" updatable="true" table="PURCHASE_ORDER"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="PURCHASE_ORDER"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductPK" abs="false" class="Product" v="true" m="false" rootElement="_1489411733819171" id="_1489411733819175">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="java.math.BigDecimal" v="true" name="purchaseCost" id="_1489411733819196">
                <jpa:bv/>
                <jpa:column name="PURCHASE_COST" unique="false" nullable="true" insertable="true" updatable="true" table="PRODUCT" precision="12" scale="2"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="Integer" v="true" name="quantityOnHand" id="_1489411733819197">
                <jpa:bv/>
                <jpa:column name="QUANTITY_ON_HAND" unique="false" nullable="true" insertable="true" updatable="true" table="PRODUCT"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="java.math.BigDecimal" v="true" name="markup" id="_1489411733819198">
                <jpa:bv/>
                <jpa:column name="MARKUP" unique="false" nullable="true" insertable="true" updatable="true" table="PRODUCT" precision="4" scale="2"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="available" id="_1489411733819199">
                <jpa:bv/>
                <jpa:column name="AVAILABLE" unique="false" nullable="true" insertable="true" updatable="true" table="PRODUCT" length="5"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="description" id="_1489411733819200">
                <jpa:bv/>
                <jpa:column name="DESCRIPTION" unique="false" nullable="true" insertable="true" updatable="true" table="PRODUCT" length="50"/>
            </jpa:basic>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_1489411733819177" connected-attribute-id="_1489411733819228" v="true" name="manufacturerId" id="_1489411733819202">
                <jpa:bv/>
                <jpa:join-column name="MANUFACTURER_ID" rc="MANUFACTURER_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_1489411733819178" connected-attribute-id="_1489411733819232" v="true" name="productCode" id="_1489411733819203">
                <jpa:bv/>
                <jpa:join-column name="PRODUCT_CODE" rc="PROD_CODE" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_1489411733819174" connected-attribute-id="_1489411733819194" v="true" name="purchaseOrderCollection" id="_1489411733819201">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Integer" v="true" name="productId" id="_1489411733819195">
                <jpa:bv/>
                <jpa:column name="PRODUCT_ID" unique="false" nullable="false" insertable="true" updatable="true" table="PRODUCT"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="PRODUCT"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="CustomerPK" abs="false" class="Customer" v="true" m="false" rootElement="_1489411733819171" id="_1489411733819176">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="String" v="true" name="name" id="_1489411733819205">
                <jpa:bv/>
                <jpa:column name="NAME" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="30"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="addressline1" id="_1489411733819206">
                <jpa:bv/>
                <jpa:column name="ADDRESSLINE1" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="30"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="addressline2" id="_1489411733819207">
                <jpa:bv/>
                <jpa:column name="ADDRESSLINE2" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="30"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="city" id="_1489411733819208">
                <jpa:bv/>
                <jpa:column name="CITY" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="25"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="state" id="_1489411733819209">
                <jpa:bv/>
                <jpa:column name="STATE" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="2"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="phone" id="_1489411733819210">
                <jpa:bv/>
                <jpa:column name="PHONE" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="12"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="fax" id="_1489411733819211">
                <jpa:bv/>
                <jpa:column name="FAX" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="12"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="email" id="_1489411733819212">
                <jpa:bv/>
                <jpa:column name="EMAIL" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER" length="40"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="Integer" v="true" name="creditLimit" id="_1489411733819213">
                <jpa:bv/>
                <jpa:column name="CREDIT_LIMIT" unique="false" nullable="true" insertable="true" updatable="true" table="CUSTOMER"/>
            </jpa:basic>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_1489411733819173" connected-attribute-id="_1489411733819186" v="true" name="discountCode" id="_1489411733819215">
                <jpa:bv/>
                <jpa:join-column name="DISCOUNT_CODE" rc="DISCOUNT_CODE" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_1489411733819172" connected-attribute-id="_1489411733819183" v="true" name="zip" id="_1489411733819216">
                <jpa:bv/>
                <jpa:join-column name="ZIP" rc="ZIP_CODE" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:many-to-one>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_1489411733819174" connected-attribute-id="_1489411733819193" v="true" name="purchaseOrderCollection" id="_1489411733819214">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Integer" v="true" name="customerId" id="_1489411733819204">
                <jpa:bv/>
                <jpa:column name="CUSTOMER_ID" unique="false" nullable="false" insertable="true" updatable="true" table="CUSTOMER"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="CUSTOMER"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ManufacturerPK" abs="false" class="Manufacturer" v="true" m="false" rootElement="_1489411733819171" id="_1489411733819177">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="String" v="true" name="name" id="_1489411733819218">
                <jpa:bv/>
                <jpa:column name="NAME" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="30"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="addressline1" id="_1489411733819219">
                <jpa:bv/>
                <jpa:column name="ADDRESSLINE1" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="30"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="addressline2" id="_1489411733819220">
                <jpa:bv/>
                <jpa:column name="ADDRESSLINE2" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="30"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="city" id="_1489411733819221">
                <jpa:bv/>
                <jpa:column name="CITY" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="25"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="state" id="_1489411733819222">
                <jpa:bv/>
                <jpa:column name="STATE" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="2"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="zip" id="_1489411733819223">
                <jpa:bv/>
                <jpa:column name="ZIP" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="10"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="phone" id="_1489411733819224">
                <jpa:bv/>
                <jpa:column name="PHONE" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="12"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="fax" id="_1489411733819225">
                <jpa:bv/>
                <jpa:column name="FAX" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="12"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="email" id="_1489411733819226">
                <jpa:bv/>
                <jpa:column name="EMAIL" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="40"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="rep" id="_1489411733819227">
                <jpa:bv/>
                <jpa:column name="REP" unique="false" nullable="true" insertable="true" updatable="true" table="MANUFACTURER" length="30"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_1489411733819175" connected-attribute-id="_1489411733819202" v="true" name="productCollection" id="_1489411733819228">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Integer" v="true" name="manufacturerId" id="_1489411733819217">
                <jpa:bv/>
                <jpa:column name="MANUFACTURER_ID" unique="false" nullable="false" insertable="true" updatable="true" table="MANUFACTURER"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="MANUFACTURER"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductCodePK" abs="false" class="ProductCode" v="true" m="false" rootElement="_1489411733819171" id="_1489411733819178">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="Character" v="true" name="discountCode" id="_1489411733819230">
                <jpa:bv/>
                <jpa:column name="DISCOUNT_CODE" unique="false" nullable="false" insertable="true" updatable="true" table="PRODUCT_CODE"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" v="true" name="description" id="_1489411733819231">
                <jpa:bv/>
                <jpa:column name="DESCRIPTION" unique="false" nullable="true" insertable="true" updatable="true" table="PRODUCT_CODE" length="10"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="false" collection-type="java.util.List" connected-entity-id="_1489411733819175" connected-attribute-id="_1489411733819203" v="true" name="productCollection" id="_1489411733819232">
                <jpa:bv/>
            </jpa:one-to-many>
            <jpa:id attribute-type="String" v="true" name="prodCode" id="_1489411733819229">
                <jpa:bv/>
                <jpa:column name="PROD_CODE" unique="false" nullable="false" insertable="true" updatable="true" table="PRODUCT_CODE" length="2"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:el/>
        <jpa:table name="PRODUCT_CODE"/>
    </jpa:entity>
    <jpa:snp loc="BEFORE_PACKAGE" e="true">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:wsl>
        <jpa:ws n="Main" id="_1489411733983233">
            <i ref="_1489411733819178" x="566" y="696"/>
            <i ref="_1489411733819177" x="1109" y="696"/>
            <i ref="_1489411733819176" x="290" y="314"/>
            <i ref="_1489411733819175" x="833" y="314"/>
            <i ref="_1489411733819174" x="566" y="32"/>
            <i ref="_1489411733819173" x="32" y="32"/>
            <i ref="_1489411733819172" x="32" y="696"/>
        </jpa:ws>
    </jpa:wsl>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Hi @olmayanaergi ,
Thanks for reporting the issue, 
Please share the environment details e.g OS, Docker Machine version etc.

Duplicate  Issue Ref : #158
