### ISSUE TITLE
Enum support in DB Modeler

### ISSUE THREAD

**Issue by jShiwaniGupta** [jGauravGupta/jpamodeler#3]
Message : Exception Description: The type [class org.iproduct.polling.entity.PollStatus] for the attribute [status] on the entity class [class org.iproduct.polling.entity.Poll] is not a valid type for a serialized mapping. The attribute type must implement the Serializable interface.

StackTrace : 
Exception Description: The type [class org.iproduct.polling.entity.PollStatus] for the attribute [status] on the entity class [class org.iproduct.polling.entity.Poll] is not a valid type for a serialized mapping. The attribute type must implement the Serializable interface.
	at org.eclipse.persistence.exceptions.ValidationException.invalidTypeForSerializedAttribute(ValidationException.java:1142)
	at org.eclipse.persistence.internal.jpa.metadata.converters.SerializedMetadata.process(SerializedMetadata.java:98)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processSerialized(MappingAccessor.java:2001)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingConverter(MappingAccessor.java:1828)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.MappingAccessor.processMappingValueConverter(MappingAccessor.java:1849)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.BasicAccessor.process(BasicAccessor.java:419)
	at org.netbeans.jpa.modeler.db.accessor.BasicSpecAccessor.process(BasicSpecAccessor.java:50)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataDescriptor.processMappingAccessors(MetadataDescriptor.java:1544)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processMappingAccessors(ClassAccessor.java:1648)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processMappingAccessors(EntityAccessor.java:1240)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.process(EntityAccessor.java:699)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage2(MetadataProject.java:1808)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:573)
	at org.netbeans.db.modeler.persistence.internal.jpa.deployment.JPAMPersistenceUnitProcessor.processORMetadata(JPAMPersistenceUnitProcessor.java:49)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:211)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:148)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:155)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:61)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1645)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1635)
	at org.netbeans.jpa.modeler.specification.model.event.JPAEventListener$2.actionPerformed(JPAEventListener.java:46)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="org.iproduct.polling.entity" v="1.2" xs="false" id="_14588791590501" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity xre="false" sm="false" abs="false" class="FAlternative" visibile="true" minimized="false" rootElement="_14588791590501" id="_14588791591122">
        <annotation n="@javax.xml.bind.annotation.XmlRootElement"/>
        <annotation n="@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)"/>
        <jpa:attributes>
            <basic attribute-type="String" visibile="true" name="text" id="_14588791591235">
                <an n="@javax.validation.constraints.Size(min=1, max=255)"/>
                <an n="@javax.validation.constraints.NotNull"/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255"/>
            </basic>
            <basic optional="false" attribute-type="int" visibile="true" name="position" id="_14588791591246">
                <an n="@javax.validation.constraints.NotNull"/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true"/>
            </basic>
            <many-to-one optional="false" primaryKey="false" connected-entity-id="_145887915918913" connected-attribute-id="_145887915919216" visibile="true" name="poll" id="_14588791591257">
                <an n="@javax.xml.bind.annotation.XmlTransient"/>
                <an n="@javax.validation.constraints.NotNull"/>
            </many-to-one>
            <one-to-many own="false" collection-type="java.util.List" connected-entity-id="_14588791591608" connected-attribute-id="_145887915916011" fetch="EAGER" visibile="true" name="votes" id="_14588791591143">
                <cascade>
                    <jpa:cascade-all/>
                </cascade>
            </one-to-many>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14588791591224">
                <an n="@javax.validation.constraints.NotNull"/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="TABLE" generator="alt_gen"/>
                <jpa:table-generator name="alt_gen" table="id_gen" pk-column-name="GEN_KEY" value-column-name="GEN_VALUE" pk-column-value="alt_id" allocation-size="1"/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" sm="false" abs="false" class="Vote" visibile="true" minimized="false" rootElement="_14588791590501" id="_14588791591608">
        <annotation n="@javax.xml.bind.annotation.XmlRootElement"/>
        <annotation n="@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)"/>
        <jpa:attributes>
            <basic attribute-type="java.util.Date" visibile="true" name="voteTime" id="_14588791591609">
                <jpa:column name="vote_time" unique="false" nullable="true" insertable="true" updatable="true"/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </basic>
            <basic optional="false" attribute-type="String" visibile="true" name="email" id="_145887915916012">
                <an n="@javax.validation.constraints.NotNull"/>
                <an n="@javax.validation.constraints.Size(min=1, max=255)"/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255"/>
            </basic>
            <many-to-one optional="false" primaryKey="false" connected-entity-id="_14588791591122" connected-attribute-id="_14588791591143" visibile="true" name="fAlternative" id="_145887915916011">
                <an n="@javax.xml.bind.annotation.XmlTransient"/>
                <an n="@javax.validation.constraints.NotNull"/>
            </many-to-one>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145887915916010">
                <an n="@javax.validation.constraints.NotNull"/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="TABLE" generator="vote_gen"/>
                <jpa:table-generator name="vote_gen" table="id_gen" pk-column-name="GEN_KEY" value-column-name="GEN_VALUE" pk-column-value="vote_id" allocation-size="1"/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" sm="false" abs="false" class="Poll" visibile="true" minimized="false" rootElement="_14588791590501" id="_145887915918913">
        <annotation n="@javax.xml.bind.annotation.XmlRootElement"/>
        <annotation n="@javax.xml.bind.annotation.XmlAccessorType(javax.xml.bind.annotation.XmlAccessType.FIELD)"/>
        <jpa:attributes>
            <basic optional="false" attribute-type="String" visibile="true" name="question" id="_145887915919114"/>
            <basic optional="false" attribute-type="java.util.Date" visibile="true" name="start" id="_145887915919215">
                <an n="@javax.validation.constraints.NotNull"/>
                <jpa:column name="poll_start" unique="false" nullable="false" insertable="true" updatable="true"/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </basic>
            <basic optional="false" attribute-type="java.util.Date" visibile="true" name="end" id="_145887915919317">
                <an n="@javax.validation.constraints.NotNull"/>
                <jpa:column name="poll_end" unique="false" nullable="false" insertable="true" updatable="true"/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </basic>
            <basic optional="false" attribute-type="String" visibile="true" name="title" id="_145887915919319"/>
            <basic attribute-type="org.iproduct.polling.entity.PollStatus" visibile="true" name="status" id="_145887915919320">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true"/>
                <jpa:enumerated>ORDINAL</jpa:enumerated>
            </basic>
            <one-to-many own="false" collection-type="java.util.List" connected-entity-id="_14588791591122" connected-attribute-id="_14588791591257" fetch="EAGER" visibile="true" name="fAlternatives" id="_145887915919216">
                <cascade>
                    <jpa:cascade-all/>
                </cascade>
            </one-to-many>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145887915919318">
                <an n="@javax.validation.constraints.NotNull"/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="TABLE" generator="poll_gen"/>
                <jpa:table-generator name="poll_gen" table="id_gen" pk-column-name="GEN_KEY" value-column-name="GEN_VALUE" pk-column-value="poll_id" allocation-size="1"/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" sm="false" abs="false" class="Entity_1" visibile="true" minimized="false" rootElement="_14588791590501" id="_145887915921021">
        <annotation n="@abc.NewAnnotationType(inside=@abc.InsideAnno(innerValue=@abc.InnerInsideAnn(334)))"/>
        <jpa:attributes>
            <basic attribute-type="String" visibile="true" name="car" id="_145887915921022">
                <an n="@javax.validation.constraints.NotNull"/>
                <an n="@javax.validation.constraints.Size(min=1, max=255, message=&quot;ggg&quot;)"/>
                <an n="@abc.NewAnnotationType(inside=@abc.InsideAnno(innerValue=@abc.InnerInsideAnn(34)))"/>
            </basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145887915921023"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:diagram>
        <plane elementRef="_14588791590501">
            <shape elementRef="_14588791591122">
                <Bounds x="225.0" y="32.0" width="182.0" height="158.0"/>
            </shape>
            <shape elementRef="_14588791591608">
                <Bounds x="32.0" y="254.0" width="129.0" height="138.0"/>
            </shape>
            <shape elementRef="_145887915918913">
                <Bounds x="463.0" y="254.0" width="135.0" height="198.0"/>
            </shape>
            <shape elementRef="_145887915921021">
                <Bounds x="658.0" y="32.0" width="151.0" height="86.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Fixed : https://github.com/jGauravGupta/jpamodeler/commit/bc4d120bc06be6ff9a22d3cc5e79ec38dcae5802
