### ISSUE TITLE
IdSpecAccessor cannot be cast to ObjectAccessor

### ISSUE THREAD

**Issue by jShiwaniGupta** [jGauravGupta/JPAModeler#4]
![newjpadiagram1 jpa](https://cloud.githubusercontent.com/assets/16020088/14038944/029a77da-f27d-11e5-8d8d-bca25344f4aa.png)
Message : org.netbeans.jpa.modeler.db.accessor.IdSpecAccessor cannot be cast to org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ObjectAccessor

StackTrace : 
java.lang.ClassCastException: org.netbeans.jpa.modeler.db.accessor.IdSpecAccessor cannot be cast to org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ObjectAccessor
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ObjectAccessor.processId(ObjectAccessor.java:489)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.ObjectAccessor.processOwningMappingKeys(ObjectAccessor.java:700)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.mappings.OneToOneAccessor.process(OneToOneAccessor.java:161)
	at org.netbeans.jpa.modeler.db.accessor.OneToOneSpecAccessor.process(OneToOneSpecAccessor.java:56)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.processDerivedId(ClassAccessor.java:1619)
	at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.EntityAccessor.processDerivedId(EntityAccessor.java:993)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processAccessorsWithDerivedIDs(MetadataProject.java:1539)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage3(MetadataProject.java:1836)
	at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:577)
	at org.netbeans.db.modeler.persistence.internal.jpa.deployment.JPAMPersistenceUnitProcessor.processORMetadata(JPAMPersistenceUnitProcessor.java:49)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:211)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:148)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:155)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:61)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1645)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1635)
	at org.netbeans.jpa.modeler.specification.model.event.JPAEventListener$2.actionPerformed(JPAEventListener.java:46)
	at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
	at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
	at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
	at java.awt.Component.processEvent(Component.java:6312)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4762)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" v="1.5.3" thm="PNBColorScheme" xs="false" id="_14560493192921" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:default-class abs="false" class="SubjectPK" visibile="true" minimized="false">
        <jpa:embeddable>false</jpa:embeddable>
        <jpa:attribute attribute-type="Long" visibile="true" name="id"/>
        <jpa:attribute attribute-type="Long" visibile="true" name="roomGroup"/>
        <jpa:attribute attribute-type="Long" visibile="true" name="room"/>
    </jpa:default-class>
    <jpa:default-class abs="false" class="SyllabusItemPK" visibile="true" minimized="false">
        <jpa:embeddable>false</jpa:embeddable>
        <jpa:attribute attribute-type="Long" visibile="true" name="id"/>
        <jpa:attribute attribute-type="Long" visibile="true" name="subject"/>
    </jpa:default-class>
    <jpa:default-class abs="false" class="ProposedTimePK" visibile="true" minimized="false">
        <jpa:embeddable>false</jpa:embeddable>
        <jpa:attribute attribute-type="Long" visibile="true" name="id"/>
        <jpa:attribute attribute-type="Long" visibile="true" name="syllabus"/>
    </jpa:default-class>
    <jpa:default-class abs="false" class="ProposedTimeItemPK" visibile="true" minimized="false">
        <jpa:embeddable>false</jpa:embeddable>
        <jpa:attribute attribute-type="Long" visibile="true" name="id"/>
        <jpa:attribute attribute-type="Long" visibile="true" name="room"/>
        <jpa:attribute attribute-type="Long" visibile="true" name="subject"/>
    </jpa:default-class>
    <jpa:entity name="Room" xre="false" sm="false" abs="false" class="Room" visibile="true" minimized="false" rootElement="_14560493192921" id="_1456049326726">
        <jpa:attributes>
            <basic attribute-type="int" visibile="true" name="capacity" id="_14560493779767">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <basic optional="false" attribute-type="String" visibile="true" name="name" id="_14560493847118">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145666993545316">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="Room"/>
    </jpa:entity>
    <jpa:entity name="Subject" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="SubjectPK" sm="false" abs="false" class="Subject" visibile="true" minimized="false" rootElement="_14560493192921" id="_1456054622532">
        <jpa:attributes>
            <basic attribute-type="int" visibile="true" name="estMemberCount" id="_14560561232987">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <basic attribute-type="int" visibile="true" name="maxTimeCount" id="_14560562847918">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <basic attribute-type="String" visibile="true" name="code" id="_14560563147679">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <basic attribute-type="String" visibile="true" name="name" id="_145605632138310">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <basic attribute-type="int" visibile="true" name="semester" id="_145700460641818">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255"/>
            </basic>
            <basic optional="false" attribute-type="int" visibile="true" name="len" id="_145700530881021">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255"/>
            </basic>
            <one-to-one own="true" primaryKey="true" connected-entity-id="_1456777485100" visibile="true" name="roomGroup" id="_145700485198519"/>
            <one-to-one own="true" optional="true" primaryKey="true" connected-entity-id="_1456049326726" visibile="true" name="room" id="_145700489556820"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145666991387815">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="Subject"/>
    </jpa:entity>
    <jpa:entity name="Syllabus" xre="false" sm="false" abs="false" class="Syllabus" visibile="true" minimized="false" rootElement="_14560493192921" id="_1456080980874">
        <jpa:attributes>
            <basic attribute-type="String" visibile="true" name="name" id="_14560811379615">
                <jpa:column unique="true" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1456081150736" visibile="true" name="items" id="_145608434934137"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145666987249413">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="Syllabus"/>
    </jpa:entity>
    <jpa:entity name="SyllabusItem" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="SyllabusItemPK" sm="false" abs="false" class="SyllabusItem" visibile="true" minimized="false" rootElement="_14560493192921" id="_1456081150736">
        <jpa:attributes>
            <one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1456054622532" visibile="true" name="dependencies" id="_145665022007238"/>
            <one-to-one own="true" optional="false" primaryKey="true" connected-entity-id="_1456054622532" visibile="true" name="subject" id="_145608320246118"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145666989254214">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity name="ProposedTime" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="ProposedTimePK" sm="false" abs="false" class="ProposedTime" visibile="true" minimized="false" rootElement="_14560493192921" id="_1456083705689">
        <jpa:attributes>
            <basic attribute-type="java.sql.Timestamp" visibile="true" name="dtCreated" id="_145608723393050">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1456083885416" visibile="true" name="items" id="_145608441515638"/>
            <one-to-one own="true" optional="false" primaryKey="true" connected-entity-id="_1456080980874" visibile="true" name="syllabus" id="_145608567564149"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145667000265318">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="ProposedTime"/>
    </jpa:entity>
    <jpa:entity name="ProposedTimeItem" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="ProposedTimeItemPK" sm="false" abs="false" class="ProposedTimeItem" visibile="true" minimized="false" rootElement="_14560493192921" id="_1456083885416">
        <jpa:attributes>
            <basic attribute-type="int" visibile="true" name="day" id="_145608464572739">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <basic attribute-type="int" visibile="true" name="hour" id="_145608466981540">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <basic attribute-type="int" visibile="true" name="len" id="_145608467809541">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </basic>
            <one-to-one own="true" optional="false" primaryKey="true" connected-entity-id="_1456049326726" visibile="true" name="room" id="_145608490888445"/>
            <one-to-one own="true" optional="false" primaryKey="true" connected-entity-id="_1456054622532" visibile="true" name="subject" id="_145681812942620"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145666996310917">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="ProposedTimeItem"/>
    </jpa:entity>
    <jpa:entity name="RoomGroup" xre="false" sm="false" abs="false" class="RoomGroup" visibile="true" minimized="false" rootElement="_14560493192921" id="_1456777485100">
        <jpa:attributes>
            <basic attribute-type="String" visibile="true" name="name" id="_145677756376716"/>
            <one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1456049326726" visibile="true" name="rooms" id="_145677752572915"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_145677750392814">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="false"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:diagram id="_14560493192922">
        <plane elementRef="_14560493192921" id="_14560493192923_p">
            <shape elementRef="_1456049326726">
                <Bounds x="746.0" y="314.0" width="137.0" height="110.0"/>
            </shape>
            <shape elementRef="_1456054622532">
                <Bounds x="407.0" y="229.0" width="159.0" height="243.0"/>
            </shape>
            <shape elementRef="_1456080980874">
                <Bounds x="42.0" y="19.0" width="158.0" height="123.0"/>
            </shape>
            <shape elementRef="_1456081150736">
                <Bounds x="42.0" y="204.0" width="189.0" height="110.0"/>
            </shape>
           <shape elementRef="_1456083705689">
                <Bounds x="387.0" y="9.0" width="199.0" height="143.0"/>
            </shape>
            <shape elementRef="_1456083885416">
                <Bounds x="807.0" y="21.0" width="230.0" height="183.0"/>
            </shape>
            <shape elementRef="_1456777485100">
                <Bounds x="48.0" y="400.0" width="180.0" height="123.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Working fine with latest release v2.6.3
