### ISSUE TITLE
Error on accessing visual db

### ISSUE THREAD

**Issue by sandeep-nair** [jGauravGupta/JPAModeler#45]
Message : 
Descriptor Exceptions: 
---------------------------------------------------------

Exception [EclipseLink-48] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Multiple writable mappings exist for the field [CART.PRODUCT_ID].  Only one may be defined as writable, all others must be specified read-only.
Mapping: org.eclipse.persistence.mappings.ManyToOneMapping[Product]
Descriptor: DBRelationalDescriptor(com.shopping.cart.samplecart.entity.Cart --> [DatabaseTable(CART)])

Exception [EclipseLink-48] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Multiple writable mappings exist for the field [CART.USER_ID].  Only one may be defined as writable, all others must be specified read-only.
Mapping: org.eclipse.persistence.mappings.OneToOneMapping[User]
Descriptor: DBRelationalDescriptor(com.shopping.cart.samplecart.entity.Cart --> [DatabaseTable(CART)])

Runtime Exceptions: 
---------------------------------------------------------

StackTrace : 
Local Exception Stack: 
Exception [EclipseLink-0] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.IntegrityException
Descriptor Exceptions: 
---------------------------------------------------------

Exception [EclipseLink-48] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Multiple writable mappings exist for the field [CART.PRODUCT_ID].  Only one may be defined as writable, all others must be specified read-only.
Mapping: org.eclipse.persistence.mappings.ManyToOneMapping[Product]
Descriptor: DBRelationalDescriptor(com.shopping.cart.samplecart.entity.Cart --> [DatabaseTable(CART)])

Exception [EclipseLink-48] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Multiple writable mappings exist for the field [CART.USER_ID].  Only one may be defined as writable, all others must be specified read-only.
Mapping: org.eclipse.persistence.mappings.OneToOneMapping[User]
Descriptor: DBRelationalDescriptor(com.shopping.cart.samplecart.entity.Cart --> [DatabaseTable(CART)])

Runtime Exceptions: 
---------------------------------------------------------

	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:715)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:651)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:582)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.postConnectDatasource(DatabaseSessionImpl.java:818)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:762)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:260)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:190)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:178)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:150)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:59)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1767)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$4(JPAModelerScene.java:384)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Descriptor Exceptions: 
---------------------------------------------------------

Local Exception Stack: 
Exception [EclipseLink-48] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Multiple writable mappings exist for the field [CART.PRODUCT_ID].  Only one may be defined as writable, all others must be specified read-only.
Mapping: org.eclipse.persistence.mappings.ManyToOneMapping[Product]
Descriptor: DBRelationalDescriptor(com.shopping.cart.samplecart.entity.Cart --> [DatabaseTable(CART)])
	at org.eclipse.persistence.exceptions.DescriptorException.multipleWriteMappingsForField(DescriptorException.java:1017)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.initialize(ObjectBuilder.java:3683)
	at org.eclipse.persistence.descriptors.ClassDescriptor.initialize(ClassDescriptor.java:3238)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:692)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:651)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:582)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.postConnectDatasource(DatabaseSessionImpl.java:818)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:762)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:260)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:190)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:178)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:150)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:59)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1767)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$4(JPAModelerScene.java:384)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Local Exception Stack: 
Exception [EclipseLink-48] (Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: Multiple writable mappings exist for the field [CART.USER_ID].  Only one may be defined as writable, all others must be specified read-only.
Mapping: org.eclipse.persistence.mappings.OneToOneMapping[User]
Descriptor: DBRelationalDescriptor(com.shopping.cart.samplecart.entity.Cart --> [DatabaseTable(CART)])
	at org.eclipse.persistence.exceptions.DescriptorException.multipleWriteMappingsForField(DescriptorException.java:1017)
	at org.eclipse.persistence.internal.descriptors.ObjectBuilder.initialize(ObjectBuilder.java:3683)
	at org.eclipse.persistence.descriptors.ClassDescriptor.initialize(ClassDescriptor.java:3238)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:692)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:651)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.initializeDescriptors(DatabaseSessionImpl.java:582)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.postConnectDatasource(DatabaseSessionImpl.java:818)
	at org.eclipse.persistence.internal.sessions.DatabaseSessionImpl.loginAndDetectDatasource(DatabaseSessionImpl.java:762)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:260)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:190)
	at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:178)
	at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:150)
	at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:59)
	at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1767)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$4(JPAModelerScene.java:384)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

Runtime Exceptions: 
---------------------------------------------------------

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.shopping.cart.samplecart.entity" v="2.5" sm="false" xs="false" id="_14726195304611" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity lbl-ref="_14726195611042" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="cartPK" abs="false" class="Cart" visibile="true" minimized="false" rootElement="_14726195304611" id="_1472619561077">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="product_id" id="_14726196026284">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="int" visibile="true" name="user_id" id="_147261998941421">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="qty" id="_147261999035822">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="created" id="_147261999055823">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="modified" id="_147261999075824">
                <jpa:bv/>
            </jpa:basic>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1472619660117" visibile="true" name="Product" id="_147262050416028"/>
            <jpa:one-to-one own="true" optional="true" primaryKey="true" connected-entity-id="_1472620532259" visibile="true" name="User" id="_147262085894134"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14726195611042">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Cart.findAll">
            <jpa:query>Select e from Cart e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByProduct_id">
            <jpa:query>Select c from Cart c where c.product_id=:product_id</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByUser_id">
            <jpa:query>Select c from Cart c where c.user_id=:user_id</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByQty">
            <jpa:query>Select c from Cart c where c.qty=:qty</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByCreated">
            <jpa:query>Select c from Cart c where c.created=:created</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByModified">
            <jpa:query>Select c from Cart c where c.modified=:modified</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductPK" abs="false" class="Product" visibile="true" minimized="false" rootElement="_14726195304611" id="_1472619660117">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147261970339915">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="price" id="_147261994783817">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="description" id="_147261994891118">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="created" id="_147261994970219">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="modified" id="_147261995028620">
                <jpa:bv/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14726196601179">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Product.findAll">
            <jpa:query>Select e from Product e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByName">
            <jpa:query>Select p from Product p where p.name=:name</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByPrice">
            <jpa:query>Select p from Product p where p.price=:price</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByDescription">
            <jpa:query>Select p from Product p where p.description=:description</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByCreated">
            <jpa:query>Select p from Product p where p.created=:created</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByModified">
            <jpa:query>Select p from Product p where p.modified=:modified</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="UserPK" abs="false" class="User" visibile="true" minimized="false" rootElement="_14726195304611" id="_1472620532259">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147262054738132">
                <jpa:bv/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_147262053226029">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="User.findAll">
            <jpa:query>Select e from User e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="User.findByName">
            <jpa:query>Select e from User e where e.name=:name</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:snp e="true" loc="BEFORE_PACKAGE">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:diagram>
        <plane elementRef="_14726195304611">
            <shape elementRef="_1472619561077">
                <Bounds x="189.0" y="83.0" width="128.0" height="231.0"/>
            </shape>
            <shape elementRef="_1472619660117">
                <Bounds x="786.0" y="117.0" width="141.0" height="176.0"/>
            </shape>
            <shape elementRef="_1472620532259">
                <Bounds x="365.0" y="94.0" width="128.0" height="92.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
Issue has been detected , 
Problem : Cart have 3 pk with same name Cart.id, User.id, Product.id
Temporary fix : changed the pk column name of user and product.

It will be fixed  by automatic join column creation in upcoming release.

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.shopping.cart.samplecart.entity" v="2.5" sm="false" xs="false" id="_14726195304611" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity lbl-ref="_14726195611042" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="cartPK" abs="false" class="Cart" visibile="true" minimized="false" rootElement="_14726195304611" id="_1472619561077">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="product_id" id="_14726196026284">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="int" visibile="true" name="user_id" id="_147261998941421">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="qty" id="_147261999035822">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="created" id="_147261999055823">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="modified" id="_147261999075824">
                <jpa:bv/>
            </jpa:basic>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1472619660117" visibile="true" name="Product" id="_147262050416028"/>
            <jpa:one-to-one own="true" optional="true" primaryKey="true" connected-entity-id="_1472620532259" visibile="true" name="User" id="_147262085894134"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14726195611042">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Cart.findAll">
            <jpa:query>Select e from Cart e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByProduct_id">
            <jpa:query>Select c from Cart c where c.product_id=:product_id</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByUser_id">
            <jpa:query>Select c from Cart c where c.user_id=:user_id</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByQty">
            <jpa:query>Select c from Cart c where c.qty=:qty</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByCreated">
            <jpa:query>Select c from Cart c where c.created=:created</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Cart.findByModified">
            <jpa:query>Select c from Cart c where c.modified=:modified</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductPK" abs="false" class="Product" visibile="true" minimized="false" rootElement="_14726195304611" id="_1472619660117">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147261970339915">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="price" id="_147261994783817">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="description" id="_147261994891118">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="created" id="_147261994970219">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="modified" id="_147261995028620">
                <jpa:bv/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14726196601179">
                <jpa:bv/>
                <jpa:column name="product_id" unique="false" nullable="true" insertable="true" updatable="true"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Product.findAll">
            <jpa:query>Select e from Product e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByName">
            <jpa:query>Select p from Product p where p.name=:name</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByPrice">
            <jpa:query>Select p from Product p where p.price=:price</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByDescription">
            <jpa:query>Select p from Product p where p.description=:description</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByCreated">
            <jpa:query>Select p from Product p where p.created=:created</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByModified">
            <jpa:query>Select p from Product p where p.modified=:modified</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="UserPK" abs="false" class="User" visibile="true" minimized="false" rootElement="_14726195304611" id="_1472620532259">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147262054738132">
                <jpa:bv/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_147262053226029">
                <jpa:bv/>
                <jpa:column name="user_id" unique="false" nullable="true" insertable="true" updatable="true"/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="User.findAll">
            <jpa:query>Select e from User e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="User.findByName">
            <jpa:query>Select e from User e where e.name=:name</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:snp e="true" loc="BEFORE_PACKAGE">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:diagram>
        <plane elementRef="_14726195304611">
            <shape elementRef="_1472619561077">
                <Bounds x="189.0" y="83.0" width="128.0" height="231.0"/>
            </shape>
            <shape elementRef="_1472619660117">
                <Bounds x="365.0" y="393.0" width="141.0" height="176.0"/>
            </shape>
            <shape elementRef="_1472620532259">
                <Bounds x="365.0" y="94.0" width="128.0" height="92.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>

**Comment by jGauravGupta** [comment]
Please download latest release v2.6.8
