### ISSUE TITLE
Embeddedable and DefaultClass(EmbeddedId/IdClass) name conflict

### ISSUE THREAD

**Issue by Namphibian** [jGauravGupta/JPAModeler#46]
Hi Team.

Using the JPA modeler plug in is a great experience. I have a current project where I am am trying to visualize the database and this is the error report. Thought I would share it just in case it helps improving.

Message : org.eclipse.persistence.internal.jpa.metadata.ORMetadata.shouldOverride(ORMetadata.java:882)

StackTrace : 
java.lang.NullPointerException
    at org.eclipse.persistence.internal.jpa.metadata.ORMetadata.shouldOverride(ORMetadata.java:882)
    at org.eclipse.persistence.internal.jpa.metadata.ORMetadata.mergeORObjectLists(ORMetadata.java:645)
    at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.XMLAttributes.merge(XMLAttributes.java:390)
    at org.eclipse.persistence.internal.jpa.metadata.accessors.classes.ClassAccessor.merge(ClassAccessor.java:1201)
    at org.eclipse.persistence.internal.jpa.metadata.xml.DBEntityMappings.initPersistenceUnitClasses(DBEntityMappings.java:133)
    at org.netbeans.db.modeler.persistence.internal.jpa.metadata.JPAMMetadataProcessor.initPersistenceUnitClasses(JPAMMetadataProcessor.java:56)
    at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processEntityMappings(MetadataProcessor.java:556)
    at org.netbeans.db.modeler.persistence.internal.jpa.deployment.JPAMPersistenceUnitProcessor.processORMetadata(JPAMPersistenceUnitProcessor.java:45)
    at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:252)
    at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:190)
    at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:178)
    at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
    at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:150)
    at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:59)
    at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1767)
    at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$4(JPAModelerScene.java:384)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.namphibian.hibernatetest" v="1.5.4" sm="false" xs="false" id="_14728870445082" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:mapped-superclass xre="false" compositePrimaryKeyClass="PartyPK" abs="false" class="Party" visibile="true" minimized="false" rootElement="_14728870445082" id="_147288704501812">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="true" attribute-type="java.util.Date" visibile="true" name="createdon" id="_147288704501814">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
            </jpa:basic>
            <jpa:basic optional="true" attribute-type="String" visibile="true" name="createdby" id="_147288704501815">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:an e="true" n="@javax.validation.constraints.Size(min=1, max=255)"/>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="updatedon" id="_147288704501816">
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="updatedby" id="_147288704501817">
                <jpa:an e="true" n="@javax.validation.constraints.Size(max=255)"/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="partyid" id="_147288704501813">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
    </jpa:mapped-superclass>
    <jpa:entity xre="false" compositePrimaryKeyClass="OrganizationPK" abs="false" class="Organization" visibile="true" minimized="false" rootElement="_14728870445082" id="_14728870446803">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="java.util.Date" visibile="true" name="createdon" id="_14728870446865">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:temporal>DATE</jpa:temporal>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="createdby" id="_14728870446876">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:an e="true" n="@javax.validation.constraints.Size(min=1, max=255)"/>
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="updatedon" id="_14728870446907">
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="updatedby" id="_14728870446908">
                <jpa:an e="true" n="@javax.validation.constraints.Size(max=255)"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_14728870446919">
                <jpa:an e="true" n="@javax.validation.constraints.Size(max=128)"/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="partyid" id="_14728870446834">
                <jpa:column unique="false" nullable="false" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Organization.findAll">
            <jpa:query>SELECT o FROM Organization o</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Organization.findByPartyid">
            <jpa:query>SELECT o FROM Organization o WHERE o.partyid = :partyid</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Organization.findByCreatedon">
            <jpa:query>SELECT o FROM Organization o WHERE o.createdon = :createdon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Organization.findByCreatedby">
            <jpa:query>SELECT o FROM Organization o WHERE o.createdby = :createdby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Organization.findByUpdatedon">
            <jpa:query>SELECT o FROM Organization o WHERE o.updatedon = :updatedon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Organization.findByUpdatedby">
            <jpa:query>SELECT o FROM Organization o WHERE o.updatedby = :updatedby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Organization.findByName">
            <jpa:query>SELECT o FROM Organization o WHERE o.name = :name</jpa:query>
        </jpa:nq>
        <jpa:table catalog="oars" schema="public"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="PersonOLDPK" abs="false" class="PersonOLD" superclassId="_147288704501812" visibile="true" minimized="false" rootElement="_14728870445082" id="_147288704501610">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="surname" id="_147288704501711">
                <jpa:an e="true" n="@javax.validation.constraints.Size(max=128)"/>
            </jpa:basic>
        </jpa:attributes>
        <jpa:nq e="true" name="Person.findAll">
            <jpa:query>SELECT p FROM Person p</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person.findByPartyid">
            <jpa:query>SELECT p FROM Person p WHERE p.partyid = :partyid</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person.findByCreatedon">
            <jpa:query>SELECT p FROM Person p WHERE p.createdon = :createdon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person.findByCreatedby">
            <jpa:query>SELECT p FROM Person p WHERE p.createdby = :createdby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person.findByUpdatedon">
            <jpa:query>SELECT p FROM Person p WHERE p.updatedon = :updatedon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person.findByUpdatedby">
            <jpa:query>SELECT p FROM Person p WHERE p.updatedby = :updatedby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person.findBySurname">
            <jpa:query>SELECT p FROM Person p WHERE p.surname = :surname</jpa:query>
        </jpa:nq>
        <jpa:table catalog="oars" schema="public"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="GenderPK" abs="false" class="Gender" visibile="true" minimized="false" rootElement="_14728870445082" id="_147288704509618">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="java.util.Date" visibile="true" name="createdon" id="_147288704509720">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:temporal>TIMESTAMP</jpa:temporal>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="createdby" id="_147288704509721">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:an e="true" n="@javax.validation.constraints.Size(min=1, max=128)"/>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="updatedon" id="_147288704509722">
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="updatedby" id="_147288704509723">
                <jpa:an e="true" n="@javax.validation.constraints.Size(max=128)"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="description" id="_147288704509724">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:an e="true" n="@javax.validation.constraints.Size(min=1, max=128)"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="shortcode" id="_147288704509725">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:an e="true" n="@javax.validation.constraints.Size(min=1, max=16)"/>
            </jpa:basic>
            <jpa:one-to-many own="false" collection-type="java.util.Collection" connected-entity-id="_147288704525637" connected-attribute-id="_147288704526648" visibile="true" name="persongenderCollection" id="_147288704509726">
                <jpa:cascade>
                    <jpa:cascade-all/>
                </jpa:cascade>
            </jpa:one-to-many>
            <jpa:id attribute-type="Integer" visibile="true" name="genderid" id="_147288704509719">
                <jpa:generated-value strategy="IDENTITY"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="true" name="Gender.findAll">
            <jpa:query>SELECT g FROM Gender g</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Gender.findByGenderid">
            <jpa:query>SELECT g FROM Gender g WHERE g.genderid = :genderid</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Gender.findByCreatedon">
            <jpa:query>SELECT g FROM Gender g WHERE g.createdon = :createdon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Gender.findByCreatedby">
            <jpa:query>SELECT g FROM Gender g WHERE g.createdby = :createdby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Gender.findByUpdatedon">
            <jpa:query>SELECT g FROM Gender g WHERE g.updatedon = :updatedon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Gender.findByUpdatedby">
            <jpa:query>SELECT g FROM Gender g WHERE g.updatedby = :updatedby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Gender.findByDescription">
            <jpa:query>SELECT g FROM Gender g WHERE g.description = :description</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Gender.findByShortcode">
            <jpa:query>SELECT g FROM Gender g WHERE g.shortcode = :shortcode</jpa:query>
        </jpa:nq>
        <jpa:table catalog="oars" schema="POSTGRES"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="PersonPK" abs="false" class="Person" superclassId="_147288704501812" visibile="true" minimized="false" rootElement="_14728870445082" id="_147288704519427">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="java.util.Date" visibile="true" name="dateofbirth" id="_147288704519433">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="deceaseddate" id="_147288704519434">
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="displayname" id="_147288704519535">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:an e="true" n="@javax.validation.constraints.Size(min=1, max=196)"/>
            </jpa:basic>
            <jpa:one-to-many own="false" collection-type="java.util.Collection" connected-entity-id="_147288704525637" connected-attribute-id="_147288704526649" visibile="true" name="persongenderCollection" id="_147288704519536">
                <jpa:cascade>
                    <jpa:cascade-all/>
                </jpa:cascade>
            </jpa:one-to-many>
        </jpa:attributes>
        <jpa:nq e="true" name="Person_1.findAll">
            <jpa:query>SELECT p FROM Person_1 p</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByPartyid">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.partyid = :partyid</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByCreatedon">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.createdon = :createdon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByCreatedby">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.createdby = :createdby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByUpdatedon">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.updatedon = :updatedon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByUpdatedby">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.updatedby = :updatedby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByDateofbirth">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.dateofbirth = :dateofbirth</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByDeceaseddate">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.deceaseddate = :deceaseddate</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Person_1.findByDisplayname">
            <jpa:query>SELECT p FROM Person_1 p WHERE p.displayname = :displayname</jpa:query>
        </jpa:nq>
        <jpa:table name="person" catalog="oars" schema="POSTGRES"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyType="EMBEDDEDID" compositePrimaryKeyClass="PersongenderPK" abs="false" class="Persongender" visibile="true" minimized="false" rootElement="_14728870445082" id="_147288704525637">
        <jpa:annotation e="true" n="@javax.xml.bind.annotation.XmlRootElement"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="java.util.Date" visibile="true" name="createdon" id="_147288704526543">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="createdby" id="_147288704526544">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:an e="true" n="@javax.validation.constraints.Size(min=1, max=128)"/>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="updatedon" id="_147288704526545">
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="updatedby" id="_147288704526546">
                <jpa:an e="true" n="@javax.validation.constraints.Size(max=128)"/>
            </jpa:basic>
            <jpa:basic attribute-type="java.util.Date" visibile="true" name="todate" id="_147288704526547">
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_147288704509618" connected-attribute-id="_147288704509726" visibile="true" name="gender" id="_147288704526648">
                <jpa:join-column name="genderid" unique="false" nullable="true" insertable="false" updatable="false"/>
            </jpa:many-to-one>
            <jpa:many-to-one optional="false" primaryKey="false" connected-entity-id="_147288704519427" connected-attribute-id="_147288704519536" visibile="true" name="person" id="_147288704526649"/>
            <jpa:id attribute-type="long" visibile="true" name="partyid" id="_147288704526650">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
            </jpa:id>
            <jpa:id attribute-type="int" visibile="true" name="genderid" id="_147288704526651">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
            </jpa:id>
            <jpa:id attribute-type="java.util.Date" visibile="true" name="fromdate" id="_147288704526652">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:id>
            <jpa:embedded-id connected-class-id="_147289095388312" visibile="true" name="persongenderPK" id="_147288704525638"/>
        </jpa:attributes>
        <jpa:nq e="true" name="Persongender.findAll">
            <jpa:query>SELECT p FROM Persongender p</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByCreatedon">
            <jpa:query>SELECT p FROM Persongender p WHERE p.createdon = :createdon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByCreatedby">
            <jpa:query>SELECT p FROM Persongender p WHERE p.createdby = :createdby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByUpdatedon">
            <jpa:query>SELECT p FROM Persongender p WHERE p.updatedon = :updatedon</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByUpdatedby">
            <jpa:query>SELECT p FROM Persongender p WHERE p.updatedby = :updatedby</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByPartyid">
            <jpa:query>SELECT p FROM Persongender p WHERE p.persongenderPK.partyid = :partyid</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByGenderid">
            <jpa:query>SELECT p FROM Persongender p WHERE p.persongenderPK.genderid = :genderid</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByFromdate">
            <jpa:query>SELECT p FROM Persongender p WHERE p.persongenderPK.fromdate = :fromdate</jpa:query>
        </jpa:nq>
        <jpa:nq e="true" name="Persongender.findByTodate">
            <jpa:query>SELECT p FROM Persongender p WHERE p.todate = :todate</jpa:query>
        </jpa:nq>
        <jpa:table catalog="oars" schema="POSTGRES"/>
    </jpa:entity>
    <jpa:embeddable abs="false" class="PersongenderPK" visibile="true" minimized="false" rootElement="_14728870445082" id="_147288704526539">
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="long" visibile="true" name="partyid" id="_147288704526540">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="int" visibile="true" name="genderid" id="_147288704526541">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
            </jpa:basic>
            <jpa:basic optional="false" attribute-type="java.util.Date" visibile="true" name="fromdate" id="_147288704526542">
                <jpa:an e="true" n="@javax.validation.constraints.NotNull"/>
                <jpa:temporal>DATE</jpa:temporal>
            </jpa:basic>
        </jpa:attributes>
    </jpa:embeddable>
    <jpa:c/>
    <jpa:diagram>
        <plane elementRef="_14728870445082">
            <shape elementRef="_14728870446803">
                <Bounds x="1523.0" y="32.0" width="168.0" height="176.0"/>
            </shape>
            <shape elementRef="_147288704501610">
                <Bounds x="973.0" y="404.0" width="161.0" height="58.0"/>
            </shape>
            <shape elementRef="_147288704509618">
                <Bounds x="-43.0" y="153.0" width="190.0" height="231.0"/>
            </shape>
            <shape elementRef="_147288704519427">
                <Bounds x="490.0" y="96.0" width="190.0" height="134.0"/>
            </shape>
            <shape elementRef="_147288704525637">
                <Bounds x="215.0" y="96.0" width="177.0" height="308.0"/>
            </shape>
            <shape elementRef="_147288704501812">
                <Bounds x="781.0" y="32.0" width="128.0" height="155.0"/>
            </shape>
            <shape elementRef="_147288704526539">
                <Bounds x="1198.0" y="32.0" width="197.0" height="100.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jShiwaniGupta** [comment]
Really thanks for submission .

**Comment by Namphibian** [comment]
Hi Shiwani

Just some notes. I am using PostgreSQL 9.4 as a back end. I am doing rather advanced database modelling with tables and indexes broken into file groups i.e. being split over different drives to increase IO. I also use table inheritance in PostgreSQL for some rather unusual SQL. I am going to see if I can reproduce this on a simple basis i.e. use some of these techniques on a clean small database and then send the information to you.
