### ISSUE TITLE
Error on generate MVC 1.0 + AngularJS

### ISSUE THREAD

**Issue by rafaeldev** [jGauravGupta/JPAModeler#54]
Message : JEE6+ supported

StackTrace : 
java.lang.IllegalStateException: JEE6+ supported
	at org.netbeans.jcode.generator.internal.ApplicationGeneratorFactory.newInstance(ApplicationGeneratorFactory.java:32)
	at org.netbeans.jcode.generator.JEEApplicationGenerator.generate(JEEApplicationGenerator.java:64)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:110)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:82)
	at org.netbeans.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:449)
	at org.netbeans.jcode.task.AbstractNBTask.run(AbstractNBTask.java:88)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)

ModelerFile : 
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="br.com.servtech.megazord.model" v="1.5.4" sm="false" xs="false" id="_14736953736751" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity lbl-ref="_14736953747314" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="UserPK" abs="false" class="User" visibile="true" minimized="false" rootElement="_14736953736751" id="_14736953744402">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:annotation e="true" n="@org.springframework.stereotype.Component"/>
        <jpa:annotation e="true" n="@org.springframework.context.annotation.Scope(&quot;session&quot;)"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="username" id="_14736953747314"/>
            <jpa:basic attribute-type="String" visibile="true" name="password" ui="false" id="_14736953747325">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="email" id="_147369601899043"/>
            <jpa:basic attribute-type="boolean" visibile="true" name="enabled" id="_147369603669144"/>
            <jpa:many-to-one primaryKey="true" connected-entity-id="_1473696157878" visibile="true" name="ocuppation" id="_1473710848832123"/>
            <jpa:one-to-one own="true" optional="true" primaryKey="true" connected-entity-id="_147369537717411" visibile="true" name="auth" id="_147369553321126"/>
            <jpa:id attribute-type="Long" visibile="true" name="userId" id="_14736953747293">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="users"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="ClientPK" abs="false" class="Client" visibile="true" minimized="false" rootElement="_14736953736751" id="_14736953768307">
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="code" id="_147370250176250"/>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147370266932051"/>
            <jpa:basic attribute-type="String" visibile="true" name="address" id="_147370266948852"/>
            <jpa:basic attribute-type="String" visibile="true" name="addressNumber" id="_147370266966453">
                <jpa:column name="address_number" unique="false" nullable="true" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="complement" id="_147370266983254"/>
            <jpa:basic attribute-type="String" visibile="true" name="cep" id="_147370267000055"/>
            <jpa:basic attribute-type="String" visibile="true" name="city" id="_147370267047157"/>
            <jpa:basic attribute-type="String" visibile="true" name="neighborhood" id="_147370267120858"/>
            <jpa:basic attribute-type="String" visibile="true" name="cnpj" id="_147370267137559"/>
            <jpa:basic attribute-type="String" visibile="true" name="ie" id="_147370274191160"/>
            <jpa:basic attribute-type="String" visibile="true" name="enabled" id="_147370274251261"/>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1473703134942" visibile="true" name="stateId" id="_147370323920666"/>
            <jpa:one-to-one optional="true" primaryKey="false" connected-entity-id="_1473708859159" connected-attribute-id="_1473709293622117" visibile="true" name="lot" id="_1473709293622118"/>
            <jpa:id attribute-type="Long" visibile="true" name="clientId" id="_14736953768308">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="AuthPK" abs="false" class="Auth" visibile="true" minimized="false" rootElement="_14736953736751" id="_147369537717411">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="authority" id="_147369537717512"/>
            <jpa:id attribute-type="Long" visibile="true" name="authId" id="_147369537717513">
                <jpa:generated-value/>
            </jpa:id>
        </jpa:attributes>
        <jpa:table name="authorities"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="OcuppationPK" abs="false" class="Ocuppation" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473696157878">
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147369621338448">
                <jpa:column unique="false" nullable="true" insertable="true" updatable="true" length="128" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_147369615788046"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="StatePK" abs="false" class="State" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473703134942">
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147370314402264"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_147370313494462"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="SerialPK" abs="false" class="Serial" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473704355307">
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="pattern" id="_147370440390169"/>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147370440458170"/>
            <jpa:id attribute-type="Long" visibile="true" name="serialId" id="_147370435531167">
                <jpa:generated-value/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="EquipamentPK" abs="false" class="Equipament" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473704460101">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="model" id="_147370480402774"/>
            <jpa:basic attribute-type="String" visibile="true" name="technology" id="_147370480421975"/>
            <jpa:basic attribute-type="boolean" visibile="true" name="calculate" id="_147370480440376"/>
            <jpa:basic attribute-type="String" visibile="true" name="preffixDigit" id="_147370480477977">
                <jpa:column name="preffix_digit" unique="false" nullable="true" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="fabricationYear" id="_147370480497178">
                <jpa:column name="fabrication_year" unique="false" nullable="true" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="warranty" id="_147370530452879"/>
            <jpa:one-to-many collection-type="java.util.List" connected-entity-id="_1473707650430" connected-attribute-id="_147370777269797" visibile="true" name="equipamentComponents" id="_147370777269798"/>
            <jpa:one-to-many own="true" collection-type="java.util.List" connected-entity-id="_1473704355307" visibile="true" name="serials" id="_1473708151222105"/>
            <jpa:id attribute-type="Long" visibile="true" name="equipamentId" id="_147370446010372">
                <jpa:generated-value/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ComponentPK" abs="false" class="Component" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473706236384">
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="code" id="_147370637784083"/>
            <jpa:basic attribute-type="String" visibile="true" name="description" id="_147370637808884"/>
            <jpa:basic attribute-type="String" visibile="true" name="positionCode" id="_147370637839285"/>
            <jpa:basic attribute-type="String" visibile="true" name="cash" id="_1473708196908106"/>
            <jpa:one-to-many collection-type="java.util.List" connected-entity-id="_1473707650430" connected-attribute-id="_1473708024817102" visibile="true" name="equipamentComponents" id="_1473708024818103"/>
            <jpa:id attribute-type="Long" visibile="true" name="componentId" id="_147370623638581">
                <jpa:generated-value/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="EquipamentSerialPK" abs="false" class="EquipamentComponent" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473707650430">
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="boardPosition" id="_1473708036650104">
                <jpa:column name="board_position" unique="false" nullable="true" insertable="true" updatable="true" length="255" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1473704460101" connected-attribute-id="_147370777269798" visibile="true" name="equipament" id="_147370777269797"/>
            <jpa:many-to-one optional="true" primaryKey="true" connected-entity-id="_1473706236384" connected-attribute-id="_1473708024818103" visibile="true" name="component" id="_1473708024817102"/>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_1473707885716101"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="SymptomPK" abs="false" class="Symptom" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473708712036">
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="code" id="_1473708758745109"/>
            <jpa:basic attribute-type="String" visibile="true" name="description" id="_1473708758928110"/>
            <jpa:id attribute-type="Long" visibile="true" name="symptomId" id="_1473708712038107">
                <jpa:generated-value/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="LotPK" abs="false" class="Lot" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473708859159">
        <jpa:attributes>
            <jpa:basic attribute-type="Integer" visibile="true" name="quantity" id="_1473708886645115"/>
            <jpa:basic attribute-type="String" visibile="true" name="nf" id="_1473708887092116"/>
            <jpa:basic attribute-type="java.sql.Date" visibile="true" name="date" id="_1473709404067119"/>
            <jpa:basic attribute-type="String" visibile="true" name="observation" id="_1473709656792120"/>
            <jpa:one-to-one own="true" optional="true" primaryKey="true" connected-entity-id="_14736953768307" connected-attribute-id="_1473709293622118" visibile="true" name="client" id="_1473709293622117"/>
            <jpa:id attribute-type="Long" visibile="true" name="lotId" id="_1473708859162112">
                <jpa:generated-value/>
            </jpa:id>
        </jpa:attributes>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="LotEquipamentPK" abs="false" class="LotEquipament" visibile="true" minimized="false" rootElement="_14736953736751" id="_1473709759861">
        <jpa:attributes>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_1473709759861121"/>
        </jpa:attributes>
    </jpa:entity>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:diagram>
        <plane elementRef="_14736953736751">
            <shape elementRef="_14736953744402">
                <Bounds x="32.0" y="32.0" width="128.0" height="210.0"/>
            </shape>
            <shape elementRef="_14736953768307">
                <Bounds x="514.0" y="598.0" width="141.0" height="357.0"/>
            </shape>
            <shape elementRef="_147369537717411">
                <Bounds x="193.0" y="32.0" width="128.0" height="92.0"/>
            </shape>
            <shape elementRef="_1473696157878">
                <Bounds x="353.0" y="32.0" width="161.0" height="92.0"/>
            </shape>
            <shape elementRef="_1473703134942">
                <Bounds x="707.0" y="598.0" width="128.0" height="92.0"/>
            </shape>
            <shape elementRef="_1473704355307">
                <Bounds x="31.0" y="577.0" width="129.0" height="113.0"/>
            </shape>
            <shape elementRef="_1473704460101">
                <Bounds x="32.0" y="273.0" width="195.0" height="252.0"/>
            </shape>
            <shape elementRef="_1473706236384">
                <Bounds x="539.0" y="273.0" width="195.0" height="189.0"/>
            </shape>
            <shape elementRef="_1473707650430">
                <Bounds x="266.0" y="273.0" width="228.0" height="147.0"/>
            </shape>
            <shape elementRef="_1473708712036">
                <Bounds x="561.0" y="32.0" width="150.0" height="113.0"/>
            </shape>
            <shape elementRef="_1473708859159">
                <Bounds x="316.0" y="604.0" width="128.0" height="189.0"/>
            </shape>
            <shape elementRef="_1473709759861">
                <Bounds x="193.0" y="826.0" width="181.0" height="58.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jShiwaniGupta** [comment]
Hi @rafaeldev ,

In which project type , you are generating the source code, Is it NetBeans > Maven > Web Applocation Project : http://jpamodeler.github.io/tutorial/OFB/MVC/QuickStart/PROJECT_CAT.png
