### ISSUE TITLE
Error when add Constructor in Subclass Entity

### ISSUE THREAD

**Issue by Mobidat** [jGauravGupta/JPAModeler#62]
Message : Class name : com.zillus.finanz.jpa.entities.Modul

StackTrace : 
org.netbeans.orm.converter.compiler.InvalidDataException: Class name : com.zillus.finanz.jpa.entities.Modul
	at org.netbeans.orm.converter.compiler.ClassDefSnippet.getSnippet(ClassDefSnippet.java:354)
	at org.netbeans.orm.converter.util.ORMConverterUtil.writeSnippet(ORMConverterUtil.java:248)
	at org.netbeans.orm.converter.generator.managed.ManagedClassModuleGeneratorImpl.generateEntityClasses(ManagedClassModuleGeneratorImpl.java:119)
	at org.netbeans.orm.converter.generator.managed.ManagedClassModuleGeneratorImpl.generate(ManagedClassModuleGeneratorImpl.java:70)
	at org.netbeans.jpa.modeler.source.generator.adaptor.internal.JPASourceCodeGenerator.generate(JPASourceCodeGenerator.java:42)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.exportCode(SourceCodeGeneratorTask.java:105)
	at org.netbeans.jpa.modeler.source.generator.task.SourceCodeGeneratorTask.begin(SourceCodeGeneratorTask.java:83)
	at org.netbeans.jcode.task.AbstractNBTask.beginTask(AbstractNBTask.java:447)
	at org.netbeans.jcode.task.AbstractNBTask.run(AbstractNBTask.java:88)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
Caused by: org.apache.velocity.exception.MethodInvocationException: Invocation of method 'getSnippet' in  class org.netbeans.orm.converter.compiler.ConstructorSnippet threw exception java.lang.NullPointerException at jpatemplate.vm[line 202, column 18]
	at org.apache.velocity.runtime.parser.node.ASTMethod.handleInvocationException(ASTMethod.java:337)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:284)
	at org.apache.velocity.runtime.parser.node.ASTReference.execute(ASTReference.java:252)
	at org.apache.velocity.runtime.parser.node.ASTReference.render(ASTReference.java:332)
	at org.apache.velocity.runtime.parser.node.ASTBlock.render(ASTBlock.java:72)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:364)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:175)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:336)
	at org.apache.velocity.Template.merge(Template.java:328)
	at org.apache.velocity.Template.merge(Template.java:235)
	at org.netbeans.orm.converter.compiler.ClassDefSnippet.getSnippet(ClassDefSnippet.java:345)
	... 12 more
Caused by: java.lang.NullPointerException
	at org.netbeans.orm.converter.compiler.ConstructorSnippet.getSnippet(ConstructorSnippet.java:54)
	at sun.reflect.GeneratedMethodAccessor195.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.doInvoke(UberspectImpl.java:389)
	at org.apache.velocity.util.introspection.UberspectImpl$VelMethodImpl.invoke(UberspectImpl.java:378)
	at org.apache.velocity.runtime.parser.node.ASTMethod.execute(ASTMethod.java:270)
	... 21 more

**Comment by jGauravGupta** [comment]
Issue fixed but manual constructor creation for super class is currently required, if super class attribute is used.
