### ISSUE TITLE
Error in visualize db (missing reference column name for CompositePK )

### ISSUE THREAD

**Issue by ovilladeamigo** [jGauravGupta/JPAModeler#67]
If entity has multiple id, in click on visulize db, gerenrate opps Error screen

Message : Exception Description: 

StackTrace : 
Local Exception Stack: 
Exception [EclipseLink-0](Eclipse Persistence Services - 2.6.2.v20151217-774c696): org.netbeans.db.modeler.exception.DBValidationException
Exception Description: 
    at org.netbeans.jpa.modeler.db.accessor.OneToManySpecAccessor.process(OneToManySpecAccessor.java:64)
    at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processOwningRelationshipAccessors(MetadataProject.java:1595)
    at org.eclipse.persistence.internal.jpa.metadata.MetadataProject.processStage3(MetadataProject.java:1848)
    at org.eclipse.persistence.internal.jpa.metadata.MetadataProcessor.processORMMetadata(MetadataProcessor.java:577)
    at org.netbeans.db.modeler.persistence.internal.jpa.deployment.JPAMPersistenceUnitProcessor.processORMetadata(JPAMPersistenceUnitProcessor.java:49)
    at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.createDBMapping(DBModelerUtil.java:255)
    at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFileInternal(DBModelerUtil.java:193)
    at org.netbeans.db.modeler.specification.model.util.DBModelerUtil.loadModelerFile(DBModelerUtil.java:178)
    at org.netbeans.modeler.core.NBModelerUtil.loadModelerFile(NBModelerUtil.java:57)
    at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:143)
    at org.netbeans.db.modeler.specification.model.file.action.DBViewerActionListener.init(DBViewerActionListener.java:58)
    at org.netbeans.jpa.modeler.specification.model.util.JPAModelerUtil.openDBViewer(JPAModelerUtil.java:1566)
    at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.lambda$getPopupMenuItemList$4(JPAModelerScene.java:384)
    at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
    at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
    at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
    at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
    at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
    at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:833)
    at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:877)
    at java.awt.Component.processMouseEvent(Component.java:6533)
    at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
    at java.awt.Component.processEvent(Component.java:6298)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4889)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
    at java.awt.Container.dispatchEventImpl(Container.java:2280)
    at java.awt.Window.dispatchEventImpl(Window.java:2746)
    at java.awt.Component.dispatchEvent(Component.java:4711)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.mobilitysol.uy.mobility.food.entities" v="2.6" sm="false" xs="false" id="_14761941187181" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity lbl-ref="_14761942209122" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="ProductPK" abs="false" class="Product" visibile="true" pkg="product" minimized="false" rootElement="_14761941187181" id="_1476194220867">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="name" id="_14761943223625">
                <jpa:bv>
                    <jpa:nu/>
                    <jpa:si mi="100" ma="1"/>
                </jpa:bv>
                <jpa:column unique="false" nullable="true" insertable="true" updatable="true" length="100" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="description" id="_14761943653587">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="String" visibile="true" name="photoPath" id="_1476197004000370">
                <jpa:bv/>
            </jpa:basic>
            <jpa:basic attribute-type="boolean" visibile="true" name="erased" id="_14761943778628">
                <jpa:bv/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1476194220867" visibile="true" name="products" id="_14761943063304">
                <jpa:join-table name="pro_product_product">
                    <jpa:join-column name="FOOD_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                    <jpa:inverse-join-column name="FOODS_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                </jpa:join-table>
            </jpa:one-to-many>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1476195647157" visibile="true" name="productOpcions" id="_1476196611808257">
                <jpa:join-column name="PODUCT_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14761942209122">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:id attribute-type="Long" visibile="true" name="id1" id="_1476199959308474">
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" visibile="true" name="version" id="_1476197319639376">
                <jpa:bv/>
            </jpa:version>
        </jpa:attributes>
        <jpa:nq e="false" name="Product.findAll">
            <jpa:query>Select e from Product e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByName">
            <jpa:query>Select f from Product f where f.name=:name</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByDescription">
            <jpa:query>Select f from Product f where f.description=:description</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByErased">
            <jpa:query>Select f from Product f where f.erased=:erased</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByPhotoPath">
            <jpa:query>Select p from Product p where p.photoPath=:photoPath</jpa:query>
        </jpa:nq>
        <jpa:table name="pro_product"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductCategoryPK" abs="false" class="ProductCategory" visibile="true" pkg="product" minimized="false" rootElement="_14761941187181" id="_1476195091847">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_147619510794172">
                <jpa:bv/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1476195091847" visibile="true" name="productCategories" id="_147619512257373">
                <jpa:join-column name="CATEGORY_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
            </jpa:one-to-many>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1476194220867" visibile="true" name="products" id="_1476195225350178">
                <jpa:join-table name="pro_product_category"/>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_147619509184870">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" visibile="true" name="version" id="_1476197330190377">
                <jpa:bv/>
            </jpa:version>
        </jpa:attributes>
        <jpa:nq e="false" name="ProductCategory.findAll">
            <jpa:query>Select e from ProductCategory e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ProductCategory.findByName">
            <jpa:query>Select f from ProductCategory f where f.name=:name</jpa:query>
        </jpa:nq>
        <jpa:table name="pro_category"/>
    </jpa:entity>
    <jpa:entity lbl-ref="_1476195647158208" xre="false" compositePrimaryKeyClass="ProductOpcionPK" abs="true" class="ProductOpcion" visibile="true" pkg="product" minimized="false" rootElement="_14761941187181" id="_1476195647157">
        <jpa:ts e="true"/>
        <jpa:hc e="true">
            <jpa:a>_1476195647158208</jpa:a>
        </jpa:hc>
        <jpa:eq e="true">
            <jpa:a>_1476195647158208</jpa:a>
        </jpa:eq>
        <jpa:attributes>
            <jpa:basic attribute-type="String" visibile="true" name="name" id="_1476195761054210">
                <jpa:bv>
                    <jpa:nu/>
                    <jpa:si mi="100" ma="3"/>
                </jpa:bv>
                <jpa:column unique="false" nullable="true" insertable="true" updatable="true" length="100" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:element-collection target-class="java.lang.String" collection-type="java.util.List" visibile="true" name="opcions" id="_1476196498940254">
                <jpa:bv/>
                <jpa:column unique="false" nullable="true" insertable="true" updatable="true" length="100" precision="0" scale="0"/>
                <jpa:collection-table name="pro_opcion_type"/>
            </jpa:element-collection>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_1476195647158208">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:version attribute-type="long" visibile="true" name="version" id="_1476197336359378">
                <jpa:bv/>
            </jpa:version>
        </jpa:attributes>
        <jpa:nq e="false" name="ProductOpcion.findAll">
            <jpa:query>Select e from ProductOpcion e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="ProductOpcion.findByName">
            <jpa:query>Select p from ProductOpcion p where p.name=:name</jpa:query>
        </jpa:nq>
        <jpa:table name="pro_opcion"/>
        <jpa:inheritance strategy="SINGLE_TABLE"/>
        <jpa:discriminator-column name="discriminator" discriminator-type="STRING" column-definition="" length="10"/>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductOpcionChoisePK" abs="false" class="ProductOpcionChoise" superclassId="_1476195647157" visibile="true" pkg="product" minimized="false" rootElement="_14761941187181" id="_1476195821447">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes/>
        <jpa:nq e="false" name="ProductOpcionChoise.findAll">
            <jpa:query>Select e from ProductOpcionChoise e</jpa:query>
        </jpa:nq>
        <jpa:discriminator-value>CHOISE</jpa:discriminator-value>
    </jpa:entity>
    <jpa:entity xre="false" compositePrimaryKeyClass="ProductOpcionListPK" abs="false" class="ProductOpcionList" superclassId="_1476195647157" visibile="true" pkg="product" minimized="false" rootElement="_14761941187181" id="_1476196537496">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes/>
        <jpa:nq e="false" name="ProductOpcionList.findAll">
            <jpa:query>Select e from ProductOpcionList e</jpa:query>
        </jpa:nq>
        <jpa:discriminator-value>LIST</jpa:discriminator-value>
    </jpa:entity>
    <jpa:entity lbl-ref="_1476197198570371" xre="false" compositePrimaryKeyClass="PlacePK" abs="false" class="Place" visibile="true" pkg="place" minimized="false" rootElement="_14761941187181" id="_1476197198568">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_1476197198570371">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Place.findAll">
            <jpa:query>Select e from Place e</jpa:query>
        </jpa:nq>
    </jpa:entity>
    <jpa:snp e="true" loc="BEFORE_PACKAGE">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:diagram>
        <plane elementRef="_14761941187181">
            <shape elementRef="_1476194220867">
                <Bounds x="60.0" y="-4.0" width="156.0" height="249.0"/>
            </shape>
            <shape elementRef="_1476195091847">
                <Bounds x="30.0" y="302.0" width="216.0" height="170.0"/>
            </shape>
            <shape elementRef="_1476195647157">
                <Bounds x="379.0" y="-4.0" width="200.0" height="137.0"/>
            </shape>
            <shape elementRef="_1476195821447">
                <Bounds x="331.0" y="226.0" width="248.0" height="23.0"/>
            </shape>
            <shape elementRef="_1476196537496">
                <Bounds x="593.0" y="226.0" width="226.0" height="23.0"/>
            </shape>
            <shape elementRef="_1476197198568">
                <Bounds x="431.0" y="302.0" width="134.0" height="54.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>
```

**Comment by jGauravGupta** [comment]
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<jpa:entity-mappings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:java="http://jcp.org/en/jsr/detail?id=270" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:jpa="http://java.sun.com/xml/ns/persistence/orm" pkg="com.mobilitysol.uy.mobility.food.entities" v="2.6" sm="false" xs="false" id="_14761941187181" xsi:schemaLocation="http://java.sun.com/xml/ns/persistence/orm orm_2_1.xsd">
    <jpa:entity lbl-ref="_14761942209122" xre="false" compositePrimaryKeyType="IDCLASS" compositePrimaryKeyClass="ProductPK" abs="false" class="Product" visibile="true" pkg="product" minimized="false" rootElement="_14761941187181" id="_1476194220867">
        <jpa:ts e="true"/>
        <jpa:hc e="true"/>
        <jpa:eq e="true"/>
        <jpa:attributes>
            <jpa:basic optional="false" attribute-type="String" visibile="true" name="name" id="_14761943223625">
                <jpa:bv>
                    <jpa:nu/>
                    <jpa:si mi="100" ma="1"/>
                </jpa:bv>
                <jpa:column unique="false" nullable="true" insertable="true" updatable="true" length="100" precision="0" scale="0"/>
            </jpa:basic>
            <jpa:one-to-many orp="false" own="true" collection-type="java.util.List" connected-entity-id="_1476194220867" visibile="true" name="products" id="_14761943063304">
                <jpa:join-table name="pro_product_product">
                    <jpa:join-column name="FOOD_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                    <jpa:inverse-join-column name="FOODS_ID" unique="false" nullable="true" insertable="true" updatable="true"/>
                </jpa:join-table>
            </jpa:one-to-many>
            <jpa:id attribute-type="Long" visibile="true" name="id" id="_14761942209122">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
            <jpa:id attribute-type="Long" visibile="true" name="id1" id="_1476199959308474">
                <jpa:bv/>
                <jpa:generated-value strategy="AUTO"/>
            </jpa:id>
        </jpa:attributes>
        <jpa:nq e="false" name="Product.findAll">
            <jpa:query>Select e from Product e</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByName">
            <jpa:query>Select f from Product f where f.name=:name</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByDescription">
            <jpa:query>Select f from Product f where f.description=:description</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByErased">
            <jpa:query>Select f from Product f where f.erased=:erased</jpa:query>
        </jpa:nq>
        <jpa:nq e="false" name="Product.findByPhotoPath">
            <jpa:query>Select p from Product p where p.photoPath=:photoPath</jpa:query>
        </jpa:nq>
        <jpa:table name="pro_product"/>
    </jpa:entity>
    <jpa:snp e="true" loc="BEFORE_PACKAGE">/**
 * This file was generated by the JPA Modeler
 */</jpa:snp>
    <jpa:c>
        <ct>java.util.List</ct>
        <ct>java.util.Set</ct>
        <ct>java.util.Map</ct>
        <ct>java.util.Collection</ct>
    </jpa:c>
    <jpa:diagram>
        <plane elementRef="_14761941187181">
            <shape elementRef="_1476194220867">
                <Bounds x="153.0" y="113.0" width="141.0" height="147.0"/>
            </shape>
        </plane>
    </jpa:diagram>
</jpa:entity-mappings>
```

Detected Issue for future ref.

**Comment by jGauravGupta** [comment]
Hi @ovilladeamigo ,

Thanks for reporting the issue, It will be fixed soon.

Right now (temp), you just delete join columns in join table of products attribute. It will work.
Issue : In case of composite primary key, Reference column name is also required that is missing in this file.
