### ISSUE TITLE
NullPointerException with Dark Look And Feel Theme

### ISSUE THREAD

**Issue by jonyfs** [jGauravGupta/JPAModeler#93]
Message : org.netbeans.modeler.scene.vmd.AbstractPModelerScene.init(AbstractPModelerScene.java:150)

StackTrace : 
java.lang.NullPointerException
	at org.netbeans.modeler.scene.vmd.AbstractPModelerScene.init(AbstractPModelerScene.java:150)
	at org.netbeans.jpa.modeler.specification.model.scene.JPAModelerScene.init(JPAModelerScene.java:331)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:145)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:72)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.openModelerFile(ModelerFileActionListener.java:64)
	at org.netbeans.modeler.specification.model.file.action.ModelerFileActionListener.lambda$actionPerformed$0(ModelerFileActionListener.java:59)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

ModelerFile : 
```xml

```

**Comment by jGauravGupta** [comment]
Hi @jonyfs , 
Can you please share the JPA Modeler and NetBeans IDE version.

**Comment by jonyfs** [comment]
NetBeans 8.2 Jpa Modeler 2.7 macOs and Windows 10

**Comment by jGauravGupta** [comment]
Ok, so you are also getting this exception on Windows OS.
Can you please share the **third-party theme plugin name and version** .
And if possible, can you try it by uninstalling the third party theme plugin.
Same error is also reported by @	pedrohidalgo : https://github.com/jGauravGupta/JPAModeler/issues/73

**Comment by jonyfs** [comment]
Darcula Look and Fell

**Comment by jGauravGupta** [comment]
I have tried with Version: 1.5 Source: 1475611665_nb-darcula-1.5.nbm http://plugins.netbeans.org/plugin/62424/darcula-laf-for-netbeans
It is working fine , can you share your darcula plugin version.

**Comment by jonyfs** [comment]
The same version.  I detected the same problem with black themes(Dark Nimbus and Dark Metal). I changed to Mac OS X and working fine.
